// ActivityScreen.js — Bloom Postpartum App (Full Sinhala)
// Changes: smaller WS letters, 5-col memory cards, baby mood image comment,
// timed bubble pop with lives, word match 30-pool no repeat, no tile merge,
// word builder 4-level hints, pattern repeat improved UI, spot diff emoji scenes,
// no math/shape sort/letter trace, responsive coin maze, 4 new mature games
import React,{useState,useEffect,useRef,useCallback}from'react';
import{View,Text,ScrollView,TouchableOpacity,StyleSheet,Dimensions,Animated,Modal}from'react-native';
import{LinearGradient}from'expo-linear-gradient';
import{colors,spacing,radius,shadows}from'../theme';
import{ALL_ACTIVITIES}from'../services/activitiesLibrary';
const{width,height}=Dimensions.get('window');

const CongratsPopup=({visible,onClose,title='ශ්‍රේෂ්ඨයි!',msg='ඔබ අපූරුයි! 💜'})=>{
  const scale=useRef(new Animated.Value(0)).current;
  const bounce=useRef(new Animated.Value(0)).current;
  useEffect(()=>{if(visible){Animated.spring(scale,{toValue:1,friction:5,tension:90,useNativeDriver:true}).start();Animated.loop(Animated.sequence([Animated.timing(bounce,{toValue:-10,duration:400,useNativeDriver:true}),Animated.timing(bounce,{toValue:0,duration:400,useNativeDriver:true})])).start();}else{scale.setValue(0);bounce.setValue(0);}},[visible]);
  if(!visible)return null;
  return(<Modal transparent visible={visible} onRequestClose={onClose}><View style={cp.overlay}><Animated.View style={[cp.box,{transform:[{scale}]}]}><View style={cp.row}>{['🎉','🌸','✨','💜','⭐'].map((c,i)=><Text key={i} style={cp.conf}>{c}</Text>)}</View><Animated.Text style={[cp.big,{transform:[{translateY:bounce}]}]}>🌟</Animated.Text><Text style={cp.title}>{title}</Text><Text style={cp.msg}>{msg}</Text><View style={cp.row}>{['🎊','💫','🌺','🌟','💕'].map((c,i)=><Text key={i} style={cp.conf}>{c}</Text>)}</View><TouchableOpacity style={cp.btn} onPress={onClose}><LinearGradient colors={['#E91E8C','#7E57C2']} style={cp.btnIn}><Text style={cp.btnT}>🎮 නැවත!</Text></LinearGradient></TouchableOpacity></Animated.View></View></Modal>);
};
const cp=StyleSheet.create({overlay:{flex:1,backgroundColor:'rgba(0,0,0,0.6)',justifyContent:'center',alignItems:'center',padding:24},box:{backgroundColor:'white',borderRadius:26,padding:26,alignItems:'center',width:'100%',maxWidth:340},row:{flexDirection:'row',gap:6,marginBottom:10},conf:{fontSize:20},big:{fontSize:60,marginBottom:8},title:{fontSize:24,fontWeight:'900',color:'#E91E8C',marginBottom:6,textAlign:'center'},msg:{fontSize:14,color:'#555',textAlign:'center',marginBottom:14,lineHeight:22},btn:{borderRadius:999,overflow:'hidden',width:'100%'},btnIn:{paddingVertical:14,alignItems:'center'},btnT:{color:'white',fontWeight:'900',fontSize:15}});

const BreathingEx=({activity,onComplete})=>{
  const[running,setRunning]=useState(false);const[done,setDone]=useState(false);const[pi,setPi]=useState(0);const[count,setCount]=useState(0);const[cycle,setCycle]=useState(1);
  const scaleAnim=useRef(new Animated.Value(1)).current;const phases=activity.phases;const CYCLES=activity.cycles||4;
  useEffect(()=>{if(!running)return;const ph=phases[pi];setCount(ph.seconds);Animated.timing(scaleAnim,{toValue:ph.scale,duration:ph.seconds*1000,useNativeDriver:true}).start();const t=setInterval(()=>setCount(c=>c>1?c-1:c),1000);const a=setTimeout(()=>{clearInterval(t);const nx=pi+1;if(nx>=phases.length){if(cycle>=CYCLES){setRunning(false);setDone(true);onComplete?.();}else{setCycle(c=>c+1);setPi(0);}}else setPi(nx);},ph.seconds*1000);return()=>{clearInterval(t);clearTimeout(a);};},[running,pi,cycle]);
  if(done)return(<LinearGradient colors={activity.color} style={bx.done}><Text style={bx.doneEmoji}>🌸</Text><Text style={bx.doneTitle}>අපූරුයි! 🌸</Text><Text style={bx.doneMsg}>{CYCLES} වට 💜</Text></LinearGradient>);
  return(<View style={bx.cont}>{!running&&<LinearGradient colors={activity.color} style={bx.intro}><Text style={bx.introText}>{activity.intro}</Text></LinearGradient>}<View style={bx.circleWrap}><Animated.View style={[bx.circleOuter,{transform:[{scale:scaleAnim}]}]}><LinearGradient colors={activity.color} style={bx.circleInner}><Text style={bx.icon}>{activity.icon}</Text>{running&&<Text style={[bx.count,{color:activity.accent}]}>{count}</Text>}</LinearGradient></Animated.View></View>{running&&<View style={bx.info}><Text style={[bx.phaseName,{color:activity.accent}]}>{phases[pi]?.name}</Text><Text style={bx.phaseInstr}>{phases[pi]?.instruction}</Text><Text style={bx.cycleT}>වට {cycle}/{CYCLES}</Text></View>}{!running&&<TouchableOpacity style={bx.startBtn} onPress={()=>{setRunning(true);setPi(0);setCycle(1);}}><LinearGradient colors={[activity.accent,'#E91E8C']} style={bx.startBtnIn}><Text style={bx.startBtnText}>ආරම්භ ▶</Text></LinearGradient></TouchableOpacity>}</View>);
};
const GuidedAct=({activity,onComplete})=>{
  const[started,setStarted]=useState(false);const[si,setSi]=useState(0);const[tLeft,setTLeft]=useState(0);const[done,setDone]=useState(false);
  useEffect(()=>{if(!started||done)return;const step=activity.steps[si];setTLeft(step.duration);const t=setInterval(()=>setTLeft(v=>v>1?v-1:v),1000);const a=setTimeout(()=>{clearInterval(t);if(si+1>=activity.steps.length){setDone(true);onComplete?.();}else setSi(i=>i+1);},step.duration*1000);return()=>{clearInterval(t);clearTimeout(a);};},[started,si]);
  const step=activity.steps[si];const pct=started&&step?((step.duration-tLeft)/step.duration)*100:0;
  if(done)return<LinearGradient colors={activity.color} style={gd.done}><Text style={gd.doneEmoji}>🌸</Text><Text style={gd.doneTitle}>ශ්‍රේෂ්ඨයි!</Text></LinearGradient>;
  return(<View>{!started?(<><LinearGradient colors={activity.color} style={gd.intro}><Text style={gd.introText}>{activity.intro}</Text></LinearGradient><TouchableOpacity style={gd.startBtn} onPress={()=>setStarted(true)}><LinearGradient colors={[activity.accent,'#E91E8C']} style={gd.startBtnIn}><Text style={gd.startBtnText}>ආරම්භ ▶</Text></LinearGradient></TouchableOpacity></>):(<><View style={gd.dotsRow}>{activity.steps.map((_,i)=><View key={i} style={[gd.dot,i===si&&gd.dotA,i<si&&gd.dotD]}/>)}</View><LinearGradient colors={activity.color} style={gd.stepCard}><Text style={[gd.stepLabel,{color:activity.accent}]}>{step.label}</Text><Text style={gd.stepText}>{step.text}</Text></LinearGradient><View style={gd.timerRow}><View style={gd.timerCircle}><Text style={[gd.timerCount,{color:activity.accent}]}>{tLeft}</Text></View><View style={gd.timerBg}><View style={[gd.timerFill,{width:`${pct}%`,backgroundColor:activity.accent}]}/></View></View></>)}</View>);
};
const PromptsAct=({activity})=>{
  const[idx,setIdx]=useState(0);const isLast=idx===activity.prompts.length-1;
  return(<View><LinearGradient colors={activity.color} style={pr.intro}><Text style={pr.introText}>{activity.intro}</Text></LinearGradient><Text style={pr.counter}>{idx+1}/{activity.prompts.length}</Text><LinearGradient colors={['#FFF9C4','#FFF0C0']} style={pr.card}><Text style={pr.cardEmoji}>💭</Text><Text style={pr.cardText}>{activity.prompts[idx]}</Text></LinearGradient><View style={pr.btnRow}>{idx>0&&<TouchableOpacity style={pr.prev} onPress={()=>setIdx(i=>i-1)}><Text style={pr.prevT}>← ආපසු</Text></TouchableOpacity>}{!isLast?<TouchableOpacity style={pr.next} onPress={()=>setIdx(i=>i+1)}><LinearGradient colors={[activity.accent,'#E91E8C']} style={pr.nextIn}><Text style={pr.nextT}>ඊළඟ →</Text></LinearGradient></TouchableOpacity>:<LinearGradient colors={['#EDE7F6','#FCE4EC']} style={pr.done}><Text style={pr.doneT}>🌸 සම්පූර්ණ!</Text></LinearGradient>}</View></View>);
};

// WORD SEARCH (smaller lighter letters)
const WS_LISTS=[{words:['MOM','BABY','LOVE','CALM','REST','HOPE'],title:'අම්මා සහ ළදරු'},{words:['PEACE','JOY','SLEEP','CARE','WARM','SOFT'],title:'සාමය සහ සතුට'},{words:['HEART','SMILE','BRAVE','GROW','BOND','SAFE'],title:'ආදරය සහ ශක්තිය'}];
const WR=8,WC_=8;
const buildGrid=(words)=>{const grid=Array.from({length:WR},()=>Array(WC_).fill(''));const placed=[];const dirs=[[0,1],[1,0],[0,-1],[-1,0]];words.forEach(word=>{for(let a=0;a<300;a++){const dir=dirs[Math.floor(Math.random()*dirs.length)];const row=Math.floor(Math.random()*WR),col=Math.floor(Math.random()*WC_);const cells=[];let fits=true;for(let i=0;i<word.length;i++){const r=row+dir[0]*i,c=col+dir[1]*i;if(r<0||r>=WR||c<0||c>=WC_||(grid[r][c]!==''&&grid[r][c]!==word[i])){fits=false;break;}cells.push([r,c]);}if(fits){cells.forEach(([r,c],i)=>{grid[r][c]=word[i];});placed.push({word,cells});break;}}});const L='ABCDEFGHIJKLMNOPQRSTUVWXYZ';for(let r=0;r<WR;r++)for(let c=0;c<WC_;c++)if(grid[r][c]==='')grid[r][c]=L[Math.floor(Math.random()*L.length)];return{grid,placed};};
const WordSearch=()=>{
  const[listIdx,setListIdx]=useState(0);const wl=WS_LISTS[listIdx];const[pd,setPd]=useState(()=>buildGrid(wl.words));const[sel,setSel]=useState([]);const[found,setFound]=useState([]);const[flash,setFlash]=useState(false);const[won,setWon]=useState(false);
  const cellSize=Math.floor((width-spacing.md*2-16)/WC_);
  const isS=(r,c)=>sel.some(s=>s.r===r&&s.c===c);const isF=(r,c)=>found.some(fw=>{const p=pd.placed.find(x=>x.word===fw);return p&&p.cells.some(([pr,pc])=>pr===r&&pc===c);});
  const tapCell=(r,c)=>{const already=sel.findIndex(s=>s.r===r&&s.c===c);const newSel=already>=0?sel.filter((_,i)=>i!==already):[...sel,{r,c}];setSel(newSel);if(newSel.length>=2){const str=newSel.map(s=>pd.grid[s.r][s.c]).join('');const rev=[...str].reverse().join('');let matched=false;for(const{word,cells}of pd.placed){if(found.includes(word))continue;const fwd=word===str&&cells.every((c2,i)=>c2[0]===newSel[i]?.r&&c2[1]===newSel[i]?.c);const bwd=word===rev&&[...cells].reverse().every((c2,i)=>c2[0]===newSel[i]?.r&&c2[1]===newSel[i]?.c);if(fwd||bwd){const nf=[...found,word];setFound(nf);setSel([]);matched=true;if(nf.length===wl.words.length)setWon(true);break;}}if(!matched&&newSel.length>=Math.max(...wl.words.map(w=>w.length))){setFlash(true);setTimeout(()=>{setFlash(false);setSel([]);},500);}}};
  const restart=(idx)=>{const w=WS_LISTS[idx];setPd(buildGrid(w.words));setSel([]);setFound([]);setWon(false);setListIdx(idx);};
  return(<View style={ws.cont}><View style={ws.header}><Text style={ws.title}>🔤 වචන සෙවීම</Text><View style={ws.badge}><Text style={ws.badgeTxt}>{found.length}/{wl.words.length}</Text></View></View><Text style={ws.subtitle}>{wl.title}</Text>{won&&<LinearGradient colors={['#EDE7F6','#FCE4EC']} style={ws.wonCard}><Text style={ws.wonEmoji}>🎉</Text><Text style={ws.wonTitle}>සියළු සොයා ගත්තා! 💜</Text></LinearGradient>}<View style={[ws.gridWrap,{width:cellSize*WC_+10}]}>{pd.grid.map((row,r)=>(<View key={r} style={ws.gridRow}>{row.map((letter,c)=>{const s2=isS(r,c),fnd=isF(r,c),wrong=flash&&s2;return(<TouchableOpacity key={`${r},${c}`} onPress={()=>tapCell(r,c)} style={[ws.cell,{width:cellSize-3,height:cellSize-3},s2&&ws.cellSel,fnd&&ws.cellFound,wrong&&ws.cellWrong]}><Text style={[ws.cellTxt,{fontSize:Math.floor(cellSize*0.36)},fnd&&ws.cellTxtF,s2&&ws.cellTxtS]}>{letter}</Text></TouchableOpacity>);})}</View>))}</View><View style={ws.wordList}>{wl.words.map(w=>(<View key={w} style={[ws.chip,found.includes(w)&&ws.chipFound]}><Text style={[ws.chipTxt,found.includes(w)&&ws.chipTxtF]}>{found.includes(w)?'✓ ':''}{w}</Text></View>))}</View><View style={ws.diffRow}>{WS_LISTS.map((wl2,i)=>(<TouchableOpacity key={i} onPress={()=>restart(i)} style={[ws.diffBtn,listIdx===i&&ws.diffBtnOn]}><Text style={[ws.diffTxt,listIdx===i&&ws.diffTxtOn]}>{wl2.title}</Text></TouchableOpacity>))}</View><TouchableOpacity style={ws.newBtn} onPress={()=>restart(listIdx)}><Text style={ws.newBtnTxt}>↺ නව</Text></TouchableOpacity></View>);
};

// BABY INTERACTION
const BABY_RESP={talk:[{msg:'ළදරු සිනාසෙයි 🥰',mood:'happy',emoji:'😊'},{msg:'ළදරු හඬ ඇසෙනවා 💜',mood:'calm',emoji:'🥰'}],sing:[{msg:'ළදරු ඇස් වහයි 😴',mood:'sleepy',emoji:'😴'},{msg:'නළවෙයි 🎵',mood:'calm',emoji:'🎵'}],smile:[{msg:'ළදරු සිනාසෙයි! 🌸',mood:'happy',emoji:'😁'},{msg:'ඇස් දිදුලයි 💫',mood:'happy',emoji:'🤩'}],feed:[{msg:'සෙමෙන් බොයි 🍼',mood:'calm',emoji:'😌'},{msg:'නිදාගනී 💤',mood:'sleepy',emoji:'😴'}],hug:[{msg:'ළඟ හිඳියි 🤱',mood:'calm',emoji:'🤗'},{msg:'ඇඟිල්ල 🤞',mood:'happy',emoji:'💜'}],rock:[{msg:'හිනාවෙලා 💤',mood:'sleepy',emoji:'😪'},{msg:'නිදාගනී 🌙',mood:'sleepy',emoji:'😴'}]};
const MOOD_COLS={happy:['#FCE4EC','#F8BBD9'],calm:['#EDE7F6','#D1C4E9'],sleepy:['#E3F2FD','#BBDEFB']};
const BI_ACTIONS=[{key:'talk',label:'💬 කතා',color:['#EDE7F6','#D1C4E9']},{key:'sing',label:'🎵 ගී',color:['#FCE4EC','#F8BBD9']},{key:'smile',label:'😊 සිනා',color:['#E8F5E9','#C8E6C9']},{key:'feed',label:'🍼 කිරි',color:['#FFF9C4','#FFF3A0']},{key:'hug',label:'🤱 ආදරය',color:['#F3E5F5','#E1BEE7']},{key:'rock',label:'🌊 නළවන',color:['#E3F2FD','#BBDEFB']}];
const BabyInteractionGame=()=>{
  const[resp,setResp]=useState(null);const[mood,setMood]=useState('calm');const[cnt,setCnt]=useState(0);const ba=useRef(new Animated.Value(1)).current;const fa=useRef(new Animated.Value(0)).current;
  const doAction=(key)=>{const opts=BABY_RESP[key];const pick=opts[Math.floor(Math.random()*opts.length)];setResp(pick);setMood(pick.mood);setCnt(c=>c+1);Animated.sequence([Animated.timing(ba,{toValue:1.3,duration:200,useNativeDriver:true}),Animated.timing(ba,{toValue:1.0,duration:200,useNativeDriver:true})]).start();fa.setValue(0);Animated.timing(fa,{toValue:1,duration:400,useNativeDriver:true}).start();};
  return(<View style={bi.cont}><View style={bi.header}><Text style={bi.title}>👶 ළදරු බැඳීම</Text><Text style={bi.count}>{cnt} ක්‍රියා 💜</Text></View><LinearGradient colors={MOOD_COLS[mood]} style={bi.babyCard}><Animated.Text style={[bi.babyEmoji,{transform:[{scale:ba}]}]}>👶</Animated.Text><Text style={bi.moodLabel}>{mood==='happy'?'සතුටු 🌸':mood==='sleepy'?'නිදිමත 💤':'සංසුන් 💜'}</Text>{resp&&<Animated.View style={[bi.responseBox,{opacity:fa}]}><Text style={bi.responseEmoji}>{resp.emoji}</Text><Text style={bi.responseText}>{resp.msg}</Text></Animated.View>}</LinearGradient><Text style={bi.actLabel}>ඔබ?</Text><View style={bi.actGrid}>{BI_ACTIONS.map(act=>(<TouchableOpacity key={act.key} onPress={()=>doAction(act.key)} style={bi.actWrap}><LinearGradient colors={act.color} style={bi.actBtn}><Text style={bi.actBtnText}>{act.label}</Text></LinearGradient></TouchableOpacity>))}</View>{cnt>=5&&<LinearGradient colors={['#FFF9C4','#FCE4EC']} style={bi.badge}><Text style={bi.badgeText}>🌸 අපූරු! 💜</Text></LinearGradient>}</View>);
};

// MEMORY MATCH (5-col smaller cards)
const MemoryMatch=()=>{
  const MM_EMOJIS=['🍼','💜','🌙','🌸','⭐'];
  const makeCards=()=>MM_EMOJIS.flatMap((e,i)=>[{id:i*2,emoji:e,flipped:false,matched:false},{id:i*2+1,emoji:e,flipped:false,matched:false}]).sort(()=>Math.random()-0.5);
  const[cards,setCards]=useState(makeCards);const[sel,setSel]=useState([]);const[moves,setMoves]=useState(0);const[matches,setMatches]=useState(0);const[locked,setLocked]=useState(false);const[showC,setShowC]=useState(false);
  const cardW=Math.floor((width-spacing.md*2-24)/5);const cardH=Math.floor(cardW*1.15);
  const tapCard=(card)=>{if(locked||card.flipped||card.matched)return;const newCards=cards.map(c=>c.id===card.id?{...c,flipped:true}:c);setCards(newCards);const newSel=[...sel,card];if(newSel.length===2){setMoves(m=>m+1);setLocked(true);setTimeout(()=>{if(newSel[0].emoji===newSel[1].emoji){setCards(prev=>prev.map(c=>c.emoji===newSel[0].emoji?{...c,matched:true,flipped:true}:c));const nm=matches+1;setMatches(nm);if(nm===5)setTimeout(()=>setShowC(true),400);}else{setCards(prev=>prev.map(c=>newSel.some(s=>s.id===c.id)&&!c.matched?{...c,flipped:false}:c));}setSel([]);setLocked(false);},800);}else setSel(newSel);};
  const reset=()=>{setCards(makeCards());setMoves(0);setMatches(0);setSel([]);setLocked(false);setShowC(false);};
  return(<View style={mm.cont}><CongratsPopup visible={showC} onClose={reset} title="ජය! 🎉" msg={`${moves} ක්‍රීඩා 💜`}/><View style={mm.header}><Text style={mm.title}>🃏 මතක ගැළපීම</Text><View style={mm.stats}><View style={mm.statChip}><Text style={mm.statTxt}>👆{moves}</Text></View><View style={[mm.statChip,{backgroundColor:'#C8E6C9'}]}><Text style={[mm.statTxt,{color:'#2E7D32'}]}>✓{matches}/5</Text></View></View></View><Text style={mm.hint}>කාඩ් දෙකක් — ගැළපෙන සොයන්න 💜</Text><View style={mm.grid}>{cards.map(card=>(<TouchableOpacity key={card.id} onPress={()=>tapCard(card)} style={[mm.card,{width:cardW,height:cardH}]}><LinearGradient colors={card.matched?['#A5D6A7','#C8E6C9']:card.flipped?['#CE93D8','#AB47BC']:['#7E57C2','#E91E8C']} style={mm.cardInner}><Text style={{fontSize:Math.floor(cardW*0.38),textAlign:'center'}}>{(card.flipped||card.matched)?card.emoji:'💜'}</Text></LinearGradient></TouchableOpacity>))}</View><TouchableOpacity style={mm.resetBtn} onPress={reset}><Text style={mm.resetBtnT}>↺ මිශ්‍ර</Text></TouchableOpacity></View>);
};

// BABY MOOD (image comment block)
const BM_MOODS=[{emoji:'😢',correct:'කුස ගිනි 🍼',options:['කුස ගිනි 🍼','නිදිමත 💤','සතුටු 😊','ඩයිපර් 🧷'],hint:'ළදරු හඬනවා!'},{emoji:'😴',correct:'නිදිමත 💤',options:['කුස ගිනි 🍼','නිදිමත 💤','සතුටු 😊','ගෑස් 💨'],hint:'නිදිය!'},{emoji:'😊',correct:'සතුටු 😊',options:['කුස ගිනි 🍼','ගෑස් 💨','සතුටු 😊','ඩයිපර් 🧷'],hint:'හොඳින්!'},{emoji:'😣',correct:'ඩයිපර් 🧷',options:['නිදිමත 💤','සතුටු 😊','කුස ගිනි 🍼','ඩයිපර් 🧷'],hint:'ඩයිපර්!'},{emoji:'😤',correct:'ගෑස් 💨',options:['කුස ගිනි 🍼','ගෑස් 💨','සතුටු 😊','ඩයිපර් 🧷'],hint:'හොඹවන්න!'},{emoji:'🥱',correct:'වැඩිය 😵',options:['කුස ගිනි 🍼','නිදිමත 💤','වැඩිය 😵','සතුටු 😊'],hint:'නිශ්ශබ්ද!'},{emoji:'😌',correct:'සංතෘප්ති 🌸',options:['කුස ගිනි 🍼','සංතෘප්ති 🌸','ඩයිපර් 🧷','ගෑස් 💨'],hint:'හොඳින්!'}];
const BabyMoodGuess=()=>{
  const[idx,setIdx]=useState(0);const[picked,setPicked]=useState(null);const[score,setScore]=useState(0);const[total,setTotal]=useState(0);const[hint,setHint]=useState(false);
  const ba=useRef(new Animated.Value(1)).current;const mood=BM_MOODS[idx%BM_MOODS.length];const opts=useRef([...mood.options].sort(()=>Math.random()-0.5));const correct=picked===mood.correct;
  const guess=(opt)=>{if(picked)return;setPicked(opt);setTotal(t=>t+1);if(opt===mood.correct){setScore(s=>s+1);Animated.sequence([Animated.timing(ba,{toValue:1.4,duration:200,useNativeDriver:true}),Animated.timing(ba,{toValue:1.0,duration:200,useNativeDriver:true})]).start();}};
  const next=()=>{setPicked(null);setHint(false);opts.current=[...BM_MOODS[(idx+1)%BM_MOODS.length].options].sort(()=>Math.random()-0.5);setIdx(i=>i+1);ba.setValue(1);};
  return(<View style={bm.cont}><View style={bm.header}><Text style={bm.title}>😊 ළදරු හැඟීම</Text><Text style={bm.score}>{score}/{total} 💜</Text></View>
    <LinearGradient colors={['#FCE4EC','#EDE7F6']} style={bm.faceCard}>
      {/* ============================================================
          📸 REAL BABY IMAGE — REPLACE EMOJI HERE:
          import { Image } from 'react-native';
          const BABY_IMAGES = {
            '😢': require('../assets/images/baby_crying.jpg'),
            '😴': require('../assets/images/baby_sleeping.jpg'),
            '😊': require('../assets/images/baby_happy.jpg'),
            '😣': require('../assets/images/baby_uncomfortable.jpg'),
            '😤': require('../assets/images/baby_gassy.jpg'),
            '🥱': require('../assets/images/baby_overstimulated.jpg'),
            '😌': require('../assets/images/baby_content.jpg'),
          };
          Replace <Animated.Text> below with:
          <Animated.View style={{transform:[{scale:ba}]}}>
            <Image source={BABY_IMAGES[mood.emoji]}
              style={{width:120,height:120,borderRadius:60}} resizeMode="cover"/>
          </Animated.View>
          ============================================================ */}
      <Animated.Text style={[bm.babyFace,{transform:[{scale:ba}]}]}>{mood.emoji}</Animated.Text>
      <Text style={bm.faceLabel}>👶 ළදරු…</Text>{picked&&<View style={[bm.resultBadge,correct?bm.correctBadge:bm.wrongBadge]}><Text style={bm.resultText}>{correct?'✓ නිවැරදි! 🌸':'✗ නැහැ!'}</Text></View>}{hint&&<Text style={bm.hintText}>{mood.hint}</Text>}
    </LinearGradient>
    <View style={bm.options}>{opts.current.map(opt=>(<TouchableOpacity key={opt} onPress={()=>guess(opt)} disabled={!!picked} style={[bm.optBtn,picked===opt&&correct&&bm.optCorrect,picked===opt&&!correct&&bm.optWrong,picked&&opt===mood.correct&&bm.optCorrect]}><Text style={bm.optText}>{opt}</Text></TouchableOpacity>))}</View><View style={bm.btnRow}>{!picked&&<TouchableOpacity style={bm.hintBtn} onPress={()=>setHint(true)}><Text style={bm.hintBtnT}>💡 ඉඟිය</Text></TouchableOpacity>}{picked&&<TouchableOpacity style={bm.nextBtn} onPress={next}><LinearGradient colors={['#7E57C2','#E91E8C']} style={bm.nextBtnIn}><Text style={bm.nextBtnT}>ඊළඟ →</Text></LinearGradient></TouchableOpacity>}</View></View>);
};
// MATURE GAME 1: EMOTION JOURNAL
const EMOTIONS=[{emoji:'😔',label:'දුකයි',color:['#E3F2FD','#BBDEFB'],reflection:'ඔබේ හැඟීම් ස්වාභාවිකයි 💙'},{emoji:'😤',label:'කෝප',color:['#FFEBEE','#FFCDD2'],reflection:'කෝපය සාමාන්‍ය. ඇවිදින්න 🌿'},{emoji:'😴',label:'ශ්‍රාන්ත',color:['#F3E5F5','#E1BEE7'],reflection:'නිදාගන්න 💜'},{emoji:'😟',label:'කාංසා',color:['#FFF9C4','#FFF3A0'],reflection:'ශ්වාස ගන්න. ආරක්ෂිතයි ⭐'},{emoji:'😊',label:'සතුටු',color:['#E8F5E9','#C8E6C9'],reflection:'ඔබේ සතුට ආශිර්වාදයකි! 🌸'},{emoji:'🥹',label:'කෘතඥ',color:['#FCE4EC','#F8BBD9'],reflection:'කෘතඥභාවය ශක්‍යතාව! 💜'},{emoji:'😐',label:'නොදනිමි',color:['#EEEEEE','#F5F5F5'],reflection:'හැඟීම් වෙනස් 🌙'},{emoji:'💪',label:'ශක්‍ය',color:['#E8F5E9','#A5D6A7'],reflection:'ශ්‍රේෂ්ඨ අම්මා! 🏆'}];
// SELF CARE QUEST
const SC_TASKS=[{id:1,icon:'💧',label:'වතුර',pts:10},{id:2,icon:'🍎',label:'ආහාර',pts:15},{id:3,icon:'😴',label:'විනාඩි 10 නිදා',pts:20},{id:4,icon:'🌸',label:'ශ්වාස 3',pts:10},{id:5,icon:'🚶',label:'ඇවිදීම',pts:15},{id:6,icon:'💜',label:'ආදර වදන',pts:20},{id:7,icon:'🛁',label:'ස්නාන',pts:15},{id:8,icon:'📞',label:'ඇමතීම',pts:10}];
const SC_BADGES=[{threshold:20,emoji:'🌱',label:'බීජය'},{threshold:50,emoji:'🌸',label:'පිපෙන'},{threshold:80,emoji:'🌺',label:'දීප්තිමත්'},{threshold:115,emoji:'⭐',label:'තරුව'}];
const SelfCareQuest=()=>{
  const[done,setDone]=useState([]);const[pts,setPts]=useState(0);const[newBadge,setNB]=useState(null);
  const toggle=(task)=>{if(done.includes(task.id)){setDone(p=>p.filter(id=>id!==task.id));setPts(p=>p-task.pts);}else{const np=pts+task.pts;setDone(p=>[...p,task.id]);setPts(np);const b=[...SC_BADGES].reverse().find(b=>np>=b.threshold);const pb=[...SC_BADGES].reverse().find(b=>pts>=b.threshold);if(b&&(!pb||pb.label!==b.label)){setNB(b);setTimeout(()=>setNB(null),3000);}}};
  const curBadge=[...SC_BADGES].reverse().find(b=>pts>=b.threshold);const nxtBadge=SC_BADGES.find(b=>b.threshold>pts);const prog=nxtBadge?Math.min((pts/nxtBadge.threshold)*100,100):100;
  return(<View style={sc.cont}><View style={sc.header}><Text style={sc.title}>🌿 ස්වයං රැකවරණය</Text><Text style={sc.pts}>{pts} ⭐</Text></View><LinearGradient colors={curBadge?['#FFF9C4','#FFF3E0']:['#F5F5F5','#EEEEEE']} style={sc.badgeCard}><Text style={sc.badgeEmoji}>{curBadge?curBadge.emoji:'🌱'}</Text><Text style={sc.badgeName}>{curBadge?curBadge.label:'ආරම්භ!'}</Text>{nxtBadge&&<><Text style={sc.nextBadgeT}>ඊළඟ: {nxtBadge.emoji}</Text><View style={sc.progressBg}><View style={[sc.progressFill,{width:`${prog}%`}]}/></View><Text style={sc.progressT}>{pts}/{nxtBadge.threshold}</Text></>}</LinearGradient>{newBadge&&<LinearGradient colors={['#FFF9C4','#FCE4EC']} style={sc.popup}><Text style={sc.popupEmoji}>{newBadge.emoji}</Text><Text style={sc.popupT}>{newBadge.label}! 🎉</Text></LinearGradient>}<Text style={sc.taskLbl}>අද:</Text>{SC_TASKS.map(task=>{const isDone=done.includes(task.id);return(<TouchableOpacity key={task.id} onPress={()=>toggle(task)}><LinearGradient colors={isDone?['#E8F5E9','#C8E6C9']:['#FAFAFA','#F5F5F5']} style={[sc.taskCard,isDone&&sc.taskDone]}><Text style={sc.taskIcon}>{task.icon}</Text><Text style={[sc.taskLabel2,isDone&&sc.taskLblDone]}>{task.label}</Text><Text style={sc.taskPts}>+{task.pts}</Text><View style={[sc.cb,isDone&&sc.cbDone]}>{isDone&&<Text style={sc.cbCheck}>✓</Text>}</View></LinearGradient></TouchableOpacity>);})}<LinearGradient colors={['#EDE7F6','#FCE4EC']} style={sc.note}><Text style={sc.noteT}>🌸 සෑම ගමනාන්තරයක්ම 💜</Text></LinearGradient></View>);
};

// BUBBLE POP (timed, flowers good, danger bad)
const FLOWER='🌸';const DANGER=['💥','🌩️','🦠','🌪️','💢','🌑'];
const BubblePop=()=>{
  const[bubbles,setBubbles]=useState([]);const[score,setScore]=useState(0);const[lives,setLives]=useState(3);const[timeLeft,setTimeLeft]=useState(45);const[running,setRunning]=useState(false);const[gameOver,setGameOver]=useState(false);const[showC,setShowC]=useState(false);
  const timerRef=useRef(null);const spawnRef=useRef(null);
  const startGame=()=>{setScore(0);setLives(3);setTimeLeft(45);setBubbles([]);setGameOver(false);setRunning(true);};
  useEffect(()=>{if(!running)return;timerRef.current=setInterval(()=>{setTimeLeft(t=>{if(t<=1){setRunning(false);setGameOver(true);clearInterval(timerRef.current);clearInterval(spawnRef.current);return 0;}return t-1;});},1000);spawnRef.current=setInterval(()=>{const isFlower=Math.random()<0.55;setBubbles(p=>[...p.slice(-18),{id:Date.now()+Math.random(),x:Math.random()*(width-100)+10,y:Math.random()*250+20,size:42+Math.random()*26,isFlower,emoji:isFlower?FLOWER:DANGER[Math.floor(Math.random()*DANGER.length)],cols:isFlower?['#FCE4EC','#F8BBD9']:['#424242','#616161']}]);},750);return()=>{clearInterval(timerRef.current);clearInterval(spawnRef.current);};},[running]);
  useEffect(()=>{if(lives<=0&&running){setRunning(false);setGameOver(true);clearInterval(timerRef.current);clearInterval(spawnRef.current);}},[lives]);
  useEffect(()=>{if(gameOver&&score>=12)setTimeout(()=>setShowC(true),400);},[gameOver]);
  const popBubble=(b)=>{setBubbles(p=>p.filter(x=>x.id!==b.id));if(b.isFlower)setScore(s=>s+1);else setLives(l=>l-1);};
  return(<View style={bp.cont}><CongratsPopup visible={showC} onClose={startGame} title="අපූරු! 🌸" msg={`🌸 ${score} මල්! 💜`}/><View style={bp.header}><Text style={bp.title}>🫧 බුබුළු</Text><View style={bp.stats}><Text style={bp.scoreT}>🌸{score}</Text><Text style={bp.livesT}>{'❤️'.repeat(lives)}{'🖤'.repeat(Math.max(0,3-lives))}</Text><Text style={bp.timerT}>⏱{timeLeft}s</Text></View></View><Text style={bp.rule}>🌸 ටොක් = +1 | ☠️ ටොක් = ජීවිතය -1</Text>{!running&&!gameOver&&(<TouchableOpacity style={bp.startBtn} onPress={startGame}><LinearGradient colors={['#E91E8C','#7E57C2']} style={bp.startBtnIn}><Text style={bp.startBtnT}>▶ ආරම්භ</Text></LinearGradient></TouchableOpacity>)}{gameOver&&(<LinearGradient colors={['#FCE4EC','#EDE7F6']} style={bp.gameOverCard}><Text style={bp.gameOverT}>{lives<=0?'💔 ජීවිත නැති!':'⏰ කාලය!'}</Text><Text style={bp.gameOverScore}>🌸{score}</Text><TouchableOpacity style={bp.retryBtn} onPress={startGame}><Text style={bp.retryBtnT}>↺ නැවත</Text></TouchableOpacity></LinearGradient>)}{running&&(<View style={bp.area}>{bubbles.map(b=>(<TouchableOpacity key={b.id} onPress={()=>popBubble(b)} style={[bp.bubble,{left:b.x,top:b.y,width:b.size,height:b.size,borderRadius:b.size/2}]}><LinearGradient colors={b.cols} style={[bp.bubbleGrad,{borderRadius:b.size/2}]}><Text style={{fontSize:b.size*0.44}}>{b.emoji}</Text></LinearGradient></TouchableOpacity>))}</View>)}</View>);
};

// WORD MATCH (30 word pool, new set per turn, no repeats)
const ALL_WM=[{w:'ආදරය',m:'💜'},{w:'සාමය',m:'🕊️'},{w:'සතුට',m:'🌸'},{w:'ශක්තිය',m:'💪'},{w:'හිනාව',m:'😊'},{w:'නිදහස',m:'🦋'},{w:'ස්වර්ණ',m:'⭐'},{w:'සෞඛ්‍ය',m:'🌿'},{w:'ළදරු',m:'👶'},{w:'අම්මා',m:'🤱'},{w:'සිහිනය',m:'🌙'},{w:'ජලය',m:'💧'},{w:'ගිනි',m:'🔥'},{w:'හදවත',m:'❤️'},{w:'ගස',m:'🌳'},{w:'මල',m:'🌺'},{w:'රේඛාව',m:'🌈'},{w:'ගීතය',m:'🎵'},{w:'ශ්‍රී',m:'🏆'},{w:'ජය',m:'🎉'},{w:'වළාකුළ',m:'☁️'},{w:'හිරු',m:'☀️'},{w:'රජු',m:'👑'},{w:'ගෙදර',m:'🏠'},{w:'ආහාර',m:'🍎'},{w:'රාත්‍රිය',m:'🌃'},{w:'සිනාව',m:'😂'},{w:'නෞකා',m:'⛵'},{w:'සුව',m:'🌿'},{w:'සංගීත',m:'🎶'}];
const WordMatchGame=()=>{
  const usedRef=useRef([]);
  const getNewPairs=useCallback(()=>{const available=ALL_WM.filter(p=>!usedRef.current.includes(p.w));const pool=available.length>=5?available:ALL_WM;if(available.length<5)usedRef.current=[];const shuffled=[...pool].sort(()=>Math.random()-0.5).slice(0,5);usedRef.current=[...usedRef.current,...shuffled.map(p=>p.w)];return shuffled;},[]);
  const[pairs,setPairs]=useState(()=>getNewPairs());const[curLeft,setCurLeft]=useState([]);const[curRight,setCurRight]=useState([]);const[sL,setSL]=useState(null);const[sR,setSR]=useState(null);const[matched,setMatched]=useState([]);const[wrong,setWrong]=useState([]);const[score,setScore]=useState(0);const[turn,setTurn]=useState(1);const[showC,setShowC]=useState(false);
  useEffect(()=>{setCurLeft([...pairs].sort(()=>Math.random()-0.5).map(p=>p.w));setCurRight([...pairs].sort(()=>Math.random()-0.5).map(p=>p.m));setMatched([]);setSL(null);setSR(null);setWrong([]);},[pairs]);
  useEffect(()=>{if(!sL||!sR)return;const hit=pairs.find(p=>p.w===sL&&p.m===sR);if(hit){setMatched(m=>[...m,sL,sR]);setScore(s=>s+10);}else{setWrong([sL,sR]);setTimeout(()=>setWrong([]),700);}setTimeout(()=>{setSL(null);setSR(null);},500);},[sL,sR]);
  useEffect(()=>{if(matched.length===pairs.length*2&&pairs.length>0)setTimeout(()=>setShowC(true),400);},[matched]);
  const nextTurn=()=>{setPairs(getNewPairs());setTurn(t=>t+1);setShowC(false);};
  return(<View style={wm.cont}><CongratsPopup visible={showC} onClose={nextTurn} title={`${turn} රවුම ජය!`} msg={`${score} ලකුණු! නව වචන! 💜`}/><View style={wm.header}><Text style={wm.title}>💬 වචන ගැළපීම</Text><Text style={wm.score}>රවුම {turn}·{score}</Text></View><Text style={wm.hint}>සිංහල→emoji 🌸</Text><View style={wm.cols}><View style={wm.col}>{curLeft.map(w=>{const isSel=sL===w,isM=matched.includes(w),isW=wrong.includes(w);return<TouchableOpacity key={w} onPress={()=>!isM&&setSL(w)} style={[wm.card,isSel&&wm.sel,isM&&wm.done2,isW&&wm.bad]}><Text style={[wm.cardT,isM&&{color:'#2E7D32'}]}>{w}</Text></TouchableOpacity>;})}</View><View style={wm.col}>{curRight.map(e=>{const isSel=sR===e,isM=matched.includes(e),isW=wrong.includes(e);return<TouchableOpacity key={e} onPress={()=>!isM&&setSR(e)} style={[wm.card,wm.cardR,isSel&&wm.sel,isM&&wm.done2,isW&&wm.bad]}><Text style={wm.emoji}>{e}</Text></TouchableOpacity>;})}</View></View></View>);
};

// WORD BUILDER (4-level progressive hints)
const WB_SETS=[{letters:['A','T','R','E','S','C'],words:['CAT','CAR','EAR','ARE','ART','SET','ACE','CARE','RACE','RATE','CREST','TRACE','CATER']},{letters:['L','O','V','E','M','R'],words:['OLE','MORE','LOVE','MOLE','OVER','ROLE','LOVER','MOVER']},{letters:['P','A','C','E','L','S'],words:['APE','CAP','ACE','LACE','PACE','CAPE','SALE','CLAP','PLACE','SCALE','SPACE']},{letters:['B','L','O','O','M','S'],words:['MOO','BOO','LOOM','BLOOM','BOOS']}];
const WordBuilder=()=>{
  const[setIdx,setSetIdx]=useState(0);const ws2=WB_SETS[setIdx];const[current,setCurrent]=useState('');const[found,setFound]=useState([]);const[msg,setMsg]=useState('');const[msgColor,setMsgColor]=useState('#2E7D32');const[hintLevel,setHintLevel]=useState(0);const[hintWord,setHintWord]=useState(null);const[showC,setShowC]=useState(false);
  const score=found.reduce((s,w)=>s+w.length*10,0);
  const submit=()=>{const w=current.toUpperCase();if(w.length<2){setMsg('ඉතා කෙටි!');setMsgColor('#C62828');setTimeout(()=>setMsg(''),1000);return;}if(found.includes(w)){setMsg('දැනටමත්!');setMsgColor('#F57F17');setTimeout(()=>setMsg(''),1000);setCurrent('');return;}if(ws2.words.includes(w)){const nf=[...found,w];setFound(nf);setMsg(`✓ "${w}" +${w.length*10}`);setMsgColor('#2E7D32');setHintLevel(0);setHintWord(null);if(nf.length>=Math.min(5,ws2.words.length))setTimeout(()=>setShowC(true),400);}else{setMsg(`"${w}" නැහැ 🤔`);setMsgColor('#7E57C2');}setTimeout(()=>setMsg(''),1800);setCurrent('');};
  const getHint=()=>{const remaining=ws2.words.filter(w=>!found.includes(w));if(!remaining.length){setMsg('සියල්ල!');setTimeout(()=>setMsg(''),1500);return;}const target=hintWord&&remaining.includes(hintWord)?hintWord:remaining[Math.floor(Math.random()*remaining.length)];setHintWord(target);const nl=hintLevel+1;setHintLevel(nl);if(nl===1)setMsg(`ඉඟිය 1: ${target.length} අකුරු 📏`);else if(nl===2)setMsg(`ඉඟිය 2: "${target[0]}" ෙන් 🔤`);else if(nl===3)setMsg(`ඉඟිය 3: "${target.slice(0,2)}…" 🔍`);else setMsg(`ඉඟිය 4: "${target}" 💡`);setMsgColor('#7E57C2');setTimeout(()=>setMsg(''),2500);};
  const nextSet=()=>{setSetIdx(i=>(i+1)%WB_SETS.length);setFound([]);setCurrent('');setHintLevel(0);setHintWord(null);setShowC(false);};
  return(<View style={wb.cont}><CongratsPopup visible={showC} onClose={nextSet} title="ශූරයා! 🔠" msg={`${score} ලකුණු! 💜`}/><View style={wb.header}><Text style={wb.title}>🔠 වචන ගොඩනැගීම</Text><Text style={wb.score}>{score} ලකුණු</Text></View><Text style={wb.subhint}>💡 4 levels: length→first→2letters→full!</Text><LinearGradient colors={['#EDE7F6','#F3E5F5']} style={wb.inputBox}><Text style={wb.inputText}>{current||'_ _ _'}</Text>{!!msg&&<Text style={[wb.msg,{color:msgColor}]}>{msg}</Text>}</LinearGradient><View style={wb.letters}>{ws2.letters.map(l=>(<TouchableOpacity key={l} style={wb.letterBtn} onPress={()=>setCurrent(c=>c+l)}><Text style={wb.letterT}>{l}</Text></TouchableOpacity>))}</View><View style={wb.actionRow}><TouchableOpacity style={wb.backBtn} onPress={()=>setCurrent(c=>c.slice(0,-1))}><Text style={wb.backBtnT}>⌫</Text></TouchableOpacity><TouchableOpacity style={wb.clearBtn} onPress={()=>setCurrent('')}><Text style={wb.clearBtnT}>✗</Text></TouchableOpacity><TouchableOpacity style={wb.submitBtn} onPress={submit}><LinearGradient colors={['#7E57C2','#E91E8C']} style={wb.submitBtnIn}><Text style={wb.submitBtnT}>✓ ඇතුළු</Text></LinearGradient></TouchableOpacity></View><TouchableOpacity style={wb.hintBtn} onPress={getHint}><Text style={wb.hintBtnT}>💡 ඉඟිය (level {Math.min(hintLevel+1,4)})</Text></TouchableOpacity><Text style={wb.foundLabel}>සොයා ({found.length}/{ws2.words.length}):</Text><View style={wb.foundList}>{found.map(w=><View key={w} style={wb.foundChip}><Text style={wb.foundChipT}>{w}</Text></View>)}</View><TouchableOpacity style={wb.newBtn} onPress={nextSet}><Text style={wb.newBtnT}>🔄 නව</Text></TouchableOpacity></View>);
};

// PATTERN REPEAT (2x3 grid, per-pad flash, progress dots)
const PAT_PADS=[{color:'#E91E8C',name:'රෝස',icon:'🌸'},{color:'#7E57C2',name:'ජම්',icon:'💜'},{color:'#2E7D32',name:'කොළ',icon:'🌿'},{color:'#1565C0',name:'නිල්',icon:'💙'},{color:'#F57F17',name:'රන්',icon:'⭐'},{color:'#C62828',name:'රතු',icon:'🔴'}];
const PatternRepeat=()=>{
  const[seq,setSeq]=useState([]);const[userSeq,setUserSeq]=useState([]);const[phase,setPhase]=useState('idle');const[active,setActive]=useState(-1);const[level,setLevel]=useState(1);const[score,setScore]=useState(0);const[showC,setShowC]=useState(false);
  const flashAnims=useRef(PAT_PADS.map(()=>new Animated.Value(1))).current;
  const showSeq=useCallback((s)=>{setPhase('showing');setActive(-1);let i=0;const show=()=>{if(i>=s.length){setTimeout(()=>{setActive(-1);setPhase('input');},500);return;}const idx=s[i];setActive(idx);Animated.sequence([Animated.timing(flashAnims[idx],{toValue:0.2,duration:280,useNativeDriver:true}),Animated.timing(flashAnims[idx],{toValue:1,duration:280,useNativeDriver:true})]).start(()=>{i++;setTimeout(show,350);});};setTimeout(show,700);},[]);
  const start=()=>{const s=[Math.floor(Math.random()*PAT_PADS.length)];setSeq(s);setUserSeq([]);setLevel(1);setScore(0);showSeq(s);};
  const tapPad=(idx)=>{if(phase!=='input')return;Animated.sequence([Animated.timing(flashAnims[idx],{toValue:0.25,duration:150,useNativeDriver:true}),Animated.timing(flashAnims[idx],{toValue:1,duration:150,useNativeDriver:true})]).start();const ns=[...userSeq,idx];setUserSeq(ns);if(ns[ns.length-1]!==seq[ns.length-1]){setPhase('wrong');return;}if(ns.length===seq.length){setScore(s=>s+level*10);setPhase('correct');if(level>=6){setTimeout(()=>setShowC(true),600);return;}setTimeout(()=>{const newSeq=[...seq,Math.floor(Math.random()*PAT_PADS.length)];setSeq(newSeq);setUserSeq([]);setLevel(l=>l+1);showSeq(newSeq);},700);}};
  const padSize=Math.floor((width-spacing.md*2-24)/3);
  return(<View style={pat.cont}><CongratsPopup visible={showC} onClose={()=>{setShowC(false);setLevel(1);start();}} title="ශූරයා! 🧠" msg={`${score} ලකුණු 💜`}/><View style={pat.header}><Text style={pat.title}>🧠 රටාව නැවත</Text><Text style={pat.score}>Lv{level}·{score}</Text></View><Text style={pat.hint}>{phase==='idle'?'▶ ආරම්භ!':phase==='showing'?'👁 බලන්න…':phase==='input'?`🎯 ඔබේ! (${userSeq.length}/${seq.length})`:phase==='correct'?'✅ නිවැරදි!':'❌ වැරදිලා!'}</Text><View style={pat.dotsRow}>{seq.map((ci,i)=>(<View key={i} style={[pat.dot,{backgroundColor:i<userSeq.length?PAT_PADS[seq[i]].color:'#ddd',width:i===userSeq.length?20:10}]}/>))}</View><View style={pat.grid}>{PAT_PADS.map((p,i)=>(<Animated.View key={i} style={{opacity:flashAnims[i]}}><TouchableOpacity onPress={()=>tapPad(i)} activeOpacity={0.8} style={[pat.pad,{width:padSize-6,height:Math.floor(padSize*0.72),backgroundColor:p.color,borderWidth:active===i?4:1.5,borderColor:active===i?'white':p.color+'80'}]}><Text style={pat.padIcon}>{p.icon}</Text><Text style={pat.padName}>{p.name}</Text></TouchableOpacity></Animated.View>))}</View>{(phase==='idle'||phase==='wrong')&&(<TouchableOpacity style={pat.startBtn} onPress={start}><LinearGradient colors={['#7E57C2','#E91E8C']} style={pat.startBtnIn}><Text style={pat.startBtnT}>{phase==='wrong'?'↺ නැවත':'▶ ආරම්භ'}</Text></LinearGradient></TouchableOpacity>)}</View>);
};

// SPOT DIFFERENCE (emoji scenes)
const SPOT_SCENES=[{title:'ළදරු කාමරය',scene:[{id:0,emoji:'🍼',x:.10,y:.15,diff:false,diffEmoji:null},{id:1,emoji:'🧸',x:.55,y:.12,diff:true,diffEmoji:'🎀'},{id:2,emoji:'🌙',x:.30,y:.05,diff:false,diffEmoji:null},{id:3,emoji:'⭐',x:.72,y:.40,diff:true,diffEmoji:'🌟'},{id:4,emoji:'🛏️',x:.40,y:.55,diff:false,diffEmoji:null},{id:5,emoji:'🌸',x:.15,y:.65,diff:true,diffEmoji:'🌺'},{id:6,emoji:'🎵',x:.68,y:.68,diff:false,diffEmoji:null},{id:7,emoji:'💜',x:.48,y:.30,diff:true,diffEmoji:'💛'}]},{title:'ළදරු උද්‍යානය',scene:[{id:0,emoji:'🌳',x:.08,y:.10,diff:false,diffEmoji:null},{id:1,emoji:'🦋',x:.60,y:.08,diff:true,diffEmoji:'🐝'},{id:2,emoji:'☀️',x:.80,y:.05,diff:false,diffEmoji:null},{id:3,emoji:'🌷',x:.25,y:.55,diff:true,diffEmoji:'🌻'},{id:4,emoji:'👶',x:.45,y:.45,diff:false,diffEmoji:null},{id:5,emoji:'🐦',x:.70,y:.50,diff:true,diffEmoji:'🦜'},{id:6,emoji:'🍀',x:.15,y:.75,diff:false,diffEmoji:null},{id:7,emoji:'🌈',x:.50,y:.80,diff:true,diffEmoji:'⛅'}]}];
const SpotDifference=()=>{
  const[sceneIdx,setSceneIdx]=useState(0);const sc2=SPOT_SCENES[sceneIdx];const diffs=sc2.scene.filter(x=>x.diff);const[found,setFound]=useState([]);const[msg,setMsg]=useState('');const[hints,setHints]=useState(0);const[showC,setShowC]=useState(false);
  const pW=(width-spacing.md*2-8)/2;const pH=Math.floor(pW*1.0);
  const tapDiff=(item,isDiff)=>{if(!isDiff)return;if(!item.diff){setMsg('🤔 ෆරක් නැහැ!');setTimeout(()=>setMsg(''),800);return;}if(found.includes(item.id))return;const nf=[...found,item.id];setFound(nf);setMsg('✅ සොයා!');setTimeout(()=>setMsg(''),800);if(nf.length===diffs.length)setTimeout(()=>setShowC(true),400);};
  const nextScene=()=>{setSceneIdx(i=>(i+1)%SPOT_SCENES.length);setFound([]);setHints(0);setMsg('');setShowC(false);};
  const useHint=()=>{if(hints>=3)return;const unfound=diffs.filter(d=>!found.includes(d.id));if(unfound.length>0){setMsg(`💡 ${unfound[0].emoji}→${unfound[0].diffEmoji}`);setTimeout(()=>setMsg(''),2500);setHints(h=>h+1);}};
  return(<View style={spd.cont}><CongratsPopup visible={showC} onClose={nextScene} title="ශූරයා! 🔍" msg={`${diffs.length} ෆරක්! 💜`}/><View style={spd.header}><Text style={spd.title}>🔍 වෙනස සොයන්න</Text><Text style={spd.score}>{found.length}/{diffs.length}</Text></View><Text style={spd.sceneTitle}>{sc2.title}</Text>{!!msg&&<Text style={[spd.msg,{color:msg.includes('✅')?'#2E7D32':msg.includes('💡')?'#7E57C2':'#C62828'}]}>{msg}</Text>}<Text style={spd.hint}>දකුණේ ෆරක් ස්පර්ශ!</Text><View style={spd.panels}>{[false,true].map(isDiff=>(<View key={String(isDiff)} style={[spd.panel,{width:pW,height:pH}]}><LinearGradient colors={isDiff?['#FFF0F5','#FFF9C4']:['#F0F8FF','#FFF9C4']} style={StyleSheet.absoluteFillObject}/><Text style={spd.panelLabel}>{isDiff?'👉 වෙනස':'📌 මුල්'}</Text>{sc2.scene.map(item=>{const isFnd=found.includes(item.id);const emoji=isDiff&&item.diff?item.diffEmoji:item.emoji;const x=item.x*(pW-36),y=item.y*(pH-48);return(<TouchableOpacity key={item.id} onPress={()=>tapDiff(item,isDiff)} style={[spd.sceneItem,{left:x,top:y+26},isFnd&&isDiff&&spd.sceneItemFound]}><Text style={{fontSize:26}}>{emoji}</Text>{isFnd&&isDiff&&<Text style={spd.foundMark}>✓</Text>}</TouchableOpacity>);})}</View>))}</View><View style={spd.actions}><TouchableOpacity style={spd.hintBtn} onPress={useHint}><Text style={spd.hintBtnT}>💡 ඉඟිය ({3-hints})</Text></TouchableOpacity><TouchableOpacity style={spd.nextBtn} onPress={nextScene}><Text style={spd.nextBtnT}>→ ඊළඟ</Text></TouchableOpacity></View></View>);
};

// SEQUENCE ORDER
const SEQ_DATA=[{title:'උදෑසන',items:['අවදි 🌅','දත් 🪥','ආහාර 🥣','ඇඳුම් 👗','සූදානම ✨']},{title:'ළදරු රැකවරණය',items:['ජාගා 👶','ඩයිපර් 🧷','කිරි 🍼','හොඹ 🫧','සෙල්ලම් 🎈']},{title:'රාත්‍රිය',items:['කාර්ය 📋','ස්නාන 🚿','තේ 🍵','කියවීම 📖','නිද 😴']}];
const SequenceOrder=()=>{
  const[seqIdx,setSeqIdx]=useState(0);const seq=SEQ_DATA[seqIdx];const[order,setOrder]=useState(()=>[...seq.items].sort(()=>Math.random()-0.5));const[sel,setSel]=useState(null);const[done,setDone]=useState(false);const[score,setScore]=useState(0);const[showC,setShowC]=useState(false);
  const correct=(o)=>{let c=0;o.forEach((it,i)=>{if(it===seq.items[i])c++;});return c;};
  const tap=(i)=>{if(done)return;if(sel===null){setSel(i);return;}if(sel===i){setSel(null);return;}const no=[...order];[no[sel],no[i]]=[no[i],no[sel]];setOrder(no);setSel(null);if(correct(no)===seq.items.length){setDone(true);setScore(s=>s+50);setTimeout(()=>setShowC(true),400);}};
  const next=()=>{const ni=(seqIdx+1)%SEQ_DATA.length;setSeqIdx(ni);setOrder([...SEQ_DATA[ni].items].sort(()=>Math.random()-0.5));setDone(false);setSel(null);setShowC(false);};
  return(<View style={so.cont}><CongratsPopup visible={showC} onClose={next} title="නිවැරදි! 🧠" msg="ශ්‍රේෂ්ඨ! 💜"/><View style={so.header}><Text style={so.title}>🧠 අනුපිළිවෙල</Text><Text style={so.score}>{score}</Text></View><Text style={so.hint}>හුවමාරු කරන්න 🌸</Text><Text style={so.seqTitle}>{seq.title}</Text>{order.map((item,i)=>(<TouchableOpacity key={i} onPress={()=>tap(i)} style={[so.item,sel===i&&so.itemSel,done&&so.itemDone]}><Text style={so.itemNum}>{i+1}</Text><Text style={so.itemT}>{item}</Text></TouchableOpacity>))}</View>);
};

// COIN MAZE (responsive to screen size)
const MAZE_GRID=[[1,1,1,1,1,1,1,1,1],[1,0,0,2,0,0,1,2,1],[1,0,1,1,1,0,1,0,1],[1,2,0,0,0,2,0,0,1],[1,1,1,0,1,1,1,0,1],[1,0,0,2,0,0,0,2,1],[1,0,1,1,1,0,1,1,1],[1,2,0,0,0,2,0,3,1],[1,1,1,1,1,1,1,1,1]];
const MZ_R=MAZE_GRID.length,MZ_C=MAZE_GRID[0].length;
const CoinMaze=()=>{
  const[pos,setPos]=useState([1,1]);const[grid,setGrid]=useState(()=>MAZE_GRID.map(r=>[...r]));const[coins,setCoins]=useState(0);const[won,setWon]=useState(false);const[showC,setShowC]=useState(false);
  const cellW=Math.floor(Math.min((width-spacing.md*2-20)/MZ_C,(height*0.38)/MZ_R));
  const move=(dr,dc)=>{if(won)return;const[r,c]=[pos[0]+dr,pos[1]+dc];if(r<0||r>=MZ_R||c<0||c>=MZ_C||grid[r][c]===1)return;const ng=grid.map(row=>[...row]);let nc=coins;if(ng[r][c]===2){ng[r][c]=0;nc++;}if(ng[r][c]===3){setWon(true);setTimeout(()=>setShowC(true),300);}setGrid(ng);setCoins(nc);setPos([r,c]);};
  const reset=()=>{setGrid(MAZE_GRID.map(r=>[...r]));setPos([1,1]);setCoins(0);setWon(false);setShowC(false);};
  return(<View style={cm.cont}><CongratsPopup visible={showC} onClose={reset} title="ජය! 🪙" msg={`${coins} කාසි! 💜`}/><View style={cm.header}><Text style={cm.title}>🪙 කාසි මාලිම</Text><Text style={cm.score}>🪙{coins}</Text></View><Text style={cm.hint}>🪙 ගෙන 🚪 සොයන්න!</Text><View style={{alignSelf:'center',marginBottom:10}}>{grid.map((row,r)=>(<View key={r} style={{flexDirection:'row'}}>{row.map((cell,c)=>{const isP=pos[0]===r&&pos[1]===c;return(<View key={c} style={[cm.cell,{width:cellW,height:cellW},cell===1&&cm.wall,isP&&cm.player,!isP&&cell===3&&cm.exit]}><Text style={{fontSize:Math.floor(cellW*0.55)}}>{isP?'🐝':cell===2?'🪙':cell===3?'🚪':''}</Text></View>);})}</View>))}</View><View style={cm.dpad}><TouchableOpacity style={cm.arrowBtn} onPress={()=>move(-1,0)}><Text style={cm.arrowT}>↑</Text></TouchableOpacity><View style={cm.arrowRow}><TouchableOpacity style={cm.arrowBtn} onPress={()=>move(0,-1)}><Text style={cm.arrowT}>←</Text></TouchableOpacity><View style={{width:48}}/><TouchableOpacity style={cm.arrowBtn} onPress={()=>move(0,1)}><Text style={cm.arrowT}>→</Text></TouchableOpacity></View><TouchableOpacity style={cm.arrowBtn} onPress={()=>move(1,0)}><Text style={cm.arrowT}>↓</Text></TouchableOpacity></View><TouchableOpacity style={cm.resetBtn} onPress={reset}><Text style={cm.resetBtnT}>↺</Text></TouchableOpacity></View>);
};

// NUMBER SEQUENCE
const NumberSeq=()=>{
  const[count,setCount]=useState(8);const[nums,setNums]=useState([]);const[nextNum,setNextNum]=useState(1);const[score,setScore]=useState(0);const[flash,setFlash]=useState(null);const[showC,setShowC]=useState(false);
  const init=useCallback((c)=>{setNums(Array.from({length:c},(_,i)=>({val:i+1,x:Math.random()*(width-spacing.md*2-58)+10,y:Math.random()*270+10,tapped:false})));setNextNum(1);setCount(c);},[]);
  useEffect(()=>{init(count);},[]);
  const tap=(n)=>{if(n.tapped)return;if(n.val===nextNum){const nn=nums.map(x=>x.val===n.val?{...x,tapped:true}:x);setNums(nn);setNextNum(v=>v+1);if(nextNum===count){setScore(s=>s+count*5);setTimeout(()=>{if(count<15){setShowC(false);init(count+2);}else setShowC(true);},600);}}else{setFlash(n.val);setTimeout(()=>setFlash(null),400);}};
  return(<View style={ns.cont}><CongratsPopup visible={showC} onClose={()=>{setShowC(false);init(8);setScore(0);}} title="ශූරයා! 🔢" msg={`${score} ලකුණු 💜`}/><View style={ns.header}><Text style={ns.title}>🔢 අංක</Text><Text style={ns.score}>{score}</Text></View><Text style={ns.hint}>1→2→3… 🌸</Text><View style={ns.infoRow}><Text style={ns.infoT}>ඊළඟ: <Text style={{color:'#7E57C2',fontWeight:'900'}}>{nextNum}</Text></Text><Text style={ns.infoT}>{count} ගණන</Text></View><View style={ns.area}>{nums.map(n=>(<TouchableOpacity key={n.val} onPress={()=>tap(n)} style={[ns.numBtn,{left:n.x,top:n.y},n.tapped&&ns.numBtnDone,flash===n.val&&ns.numBtnWrong]}><Text style={[ns.numT,n.tapped&&{color:'#2E7D32'}]}>{n.tapped?'✓':n.val}</Text></TouchableOpacity>))}</View><TouchableOpacity style={ns.resetBtn} onPress={()=>{init(8);setScore(0);}}><Text style={ns.resetBtnT}>↺</Text></TouchableOpacity></View>);
};

// ROTATION PUZZLE
const RotationPuzzle=()=>{
  const PIECES=['🌸','💜','⭐','🍀','🌙','🦋','🎵','🌺','🌈'];
  const[tiles,setTiles]=useState(()=>PIECES.map((emoji,i)=>({id:i,emoji,rotation:[0,90,180,270][Math.floor(Math.random()*4)]})));const[moves,setMoves]=useState(0);const[showC,setShowC]=useState(false);
  const won=tiles.every(t=>t.rotation===0);
  const rotate=(idx)=>{const nt=tiles.map((t,i)=>i===idx?{...t,rotation:(t.rotation+90)%360}:t);setTiles(nt);setMoves(m=>m+1);if(nt.every(t=>t.rotation===0))setTimeout(()=>setShowC(true),400);};
  const shuffle=()=>{setTiles(PIECES.map((emoji,i)=>({id:i,emoji,rotation:[90,180,270][Math.floor(Math.random()*3)]})));setMoves(0);setShowC(false);};
  const tileSize=Math.floor((width-spacing.md*2-30)/3);
  return(<View style={rp.cont}><CongratsPopup visible={showC} onClose={shuffle} title="ජය! 🔄" msg={`${moves} ක්‍රීඩා 💜`}/><View style={rp.header}><Text style={rp.title}>🔄 කරකැවිල්ල</Text><Text style={rp.score}>{moves}</Text></View><Text style={rp.hint}>ස්පර්ශ→කරකවන්න 0° 🌸</Text>{won&&<LinearGradient colors={['#E8F5E9','#C8E6C9']} style={rp.wonBanner}><Text style={rp.wonT}>🎉 සියල්ල!</Text></LinearGradient>}<View style={rp.grid}>{tiles.map((t,i)=>(<TouchableOpacity key={t.id} onPress={()=>rotate(i)} style={[rp.tile,{width:tileSize,height:tileSize},t.rotation===0&&rp.tileDone]}><Text style={{fontSize:Math.floor(tileSize*0.42),transform:[{rotate:`${t.rotation}deg`}]}}>{t.emoji}</Text><Text style={{fontSize:10,color:t.rotation===0?'#2E7D32':'#999'}}>{t.rotation}°</Text></TouchableOpacity>))}</View><TouchableOpacity style={rp.shuffleBtn} onPress={shuffle}><Text style={rp.shuffleBtnT}>↺</Text></TouchableOpacity></View>);
};

// SLIDING PUZZLE
const SlidingPuzzle=()=>{
  const SZ=3;const TOTAL=SZ*SZ;const EMOJIS=['🌸','💜','⭐','🍀','🌙','🦋','🎵','🌺'];
  const shuffleArr=(arr)=>{const a=[...arr];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};
  const[tiles,setTiles]=useState(()=>shuffleArr(Array.from({length:TOTAL},(_,i)=>i)));const[moves,setMoves]=useState(0);const[showC,setShowC]=useState(false);
  const tileSize=Math.floor((width-spacing.md*2-20)/SZ);
  const tap=(idx)=>{const empty=tiles.indexOf(TOTAL-1);const r1=Math.floor(idx/SZ),c1=idx%SZ,r2=Math.floor(empty/SZ),c2=empty%SZ;if(Math.abs(r1-r2)+Math.abs(c1-c2)!==1)return;const nt=[...tiles];[nt[idx],nt[empty]]=[nt[empty],nt[idx]];setTiles(nt);setMoves(m=>m+1);if(nt.every((v,i)=>v===i))setTimeout(()=>setShowC(true),300);};
  const reset=()=>{setTiles(shuffleArr(Array.from({length:TOTAL},(_,i)=>i)));setMoves(0);setShowC(false);};
  return(<View style={slp.cont}><CongratsPopup visible={showC} onClose={reset} title="ජය! 🧩" msg={`${moves} ක්‍රීඩා 💜`}/><View style={slp.header}><Text style={slp.title}>🧩 ස්ලයිඩ්</Text><Text style={slp.score}>{moves}</Text></View><Text style={slp.hint}>slide කරා! 🌸</Text><View style={slp.grid}>{tiles.map((val,i)=>{const isEmpty=val===TOTAL-1;return(<TouchableOpacity key={i} onPress={()=>tap(i)} style={[slp.tile,{width:tileSize,height:tileSize},isEmpty&&slp.empty,!isEmpty&&val===i&&slp.correct]}>{!isEmpty&&(<><Text style={{fontSize:Math.floor(tileSize*0.36)}}>{EMOJIS[val]}</Text><Text style={{fontSize:12,fontWeight:'900',color:val===i?'#2E7D32':'#666'}}>{val+1}</Text></>)}</TouchableOpacity>);})}</View><TouchableOpacity style={slp.resetBtn} onPress={reset}><Text style={slp.resetBtnT}>↺</Text></TouchableOpacity></View>);
};
const EmotionJournal=()=>{
  const[selected,setSelected]=useState(null);const[journal,setJournal]=useState([]);const[showRefl,setShowRefl]=useState(false);
  const scale=useRef(new Animated.Value(1)).current;
  const selectEm=(em)=>{setSelected(em);Animated.sequence([Animated.timing(scale,{toValue:1.15,duration:200,useNativeDriver:true}),Animated.timing(scale,{toValue:1,duration:200,useNativeDriver:true})]).start();setTimeout(()=>setShowRefl(true),300);};
  const saveEntry=()=>{if(!selected)return;setJournal(j=>[...j,{emoji:selected.emoji,label:selected.label,time:new Date().toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit'})}]);setSelected(null);setShowRefl(false);};
  return(<View style={ej.cont}><View style={ej.header}><Text style={ej.title}>🎭 හැඟීම් දිනපොත</Text><Text style={ej.count}>අද: {journal.length}</Text></View><Text style={ej.hint}>ඔබේ හැඟීම ස්පර්ශ කරන්න 🌸</Text>{showRefl&&selected?(<LinearGradient colors={selected.color} style={ej.reflCard}><Text style={ej.reflEmoji}>{selected.emoji}</Text><Text style={ej.reflLabel}>{selected.label}</Text><Text style={ej.reflText}>{selected.reflection}</Text><TouchableOpacity style={ej.saveBtn} onPress={saveEntry}><LinearGradient colors={['#7E57C2','#E91E8C']} style={ej.saveBtnIn}><Text style={ej.saveBtnT}>💾 සටහන්</Text></LinearGradient></TouchableOpacity><TouchableOpacity onPress={()=>{setSelected(null);setShowRefl(false);}}><Text style={ej.cancelT}>← ආපසු</Text></TouchableOpacity></LinearGradient>):(<><View style={ej.grid}>{EMOTIONS.map(em=>(<TouchableOpacity key={em.emoji} onPress={()=>selectEm(em)} style={[ej.emotionBtn,{backgroundColor:em.color[0]}]}><Text style={ej.emotionEmoji}>{em.emoji}</Text><Text style={ej.emotionLabel}>{em.label}</Text></TouchableOpacity>))}</View>{journal.length>0&&<View style={ej.journalList}><Text style={ej.journalTitle}>අද:</Text>{journal.slice(-5).map((e,i)=>(<View key={i} style={ej.journalItem}><Text style={ej.jEmoji}>{e.emoji}</Text><Text style={ej.jLabel}>{e.label}</Text><Text style={ej.jTime}>{e.time}</Text></View>))}</View>}</>)}</View>);
};

// MATURE GAME 2: MINDFUL TAP
const MT_PATTERNS=[{name:'ශ්වාස රිද්මය',cues:['ශ්වාස…','රඳවා…','හළ…','රඳවා…'],durations:[4,2,4,2],color:'#7E57C2'},{name:'සිත',cues:['ස්ථාවර…','සිතනවා…','නිදහස්…','සිතනවා…'],durations:[3,3,3,3],color:'#E91E8C'},{name:'සාමය',cues:['සාමය…','ස්නේහය…','කෘතඥ…','ළදරු…'],durations:[4,4,4,4],color:'#2E7D32'}];
const MindfulTap=()=>{
  const[patIdx,setPatIdx]=useState(0);const[running,setRunning]=useState(false);const[cueIdx,setCueIdx]=useState(0);const[timeLeft,setTimeLeft]=useState(0);const[taps,setTaps]=useState(0);const[round,setRound]=useState(1);const[done,setDone]=useState(false);
  const pat=MT_PATTERNS[patIdx];const pulse=useRef(new Animated.Value(1)).current;const loopRef=useRef(null);
  useEffect(()=>{if(!running)return;const dur=pat.durations[cueIdx];setTimeLeft(dur);loopRef.current=Animated.loop(Animated.sequence([Animated.timing(pulse,{toValue:1.3,duration:dur*500,useNativeDriver:true}),Animated.timing(pulse,{toValue:1.0,duration:dur*500,useNativeDriver:true})]));loopRef.current.start();const t=setInterval(()=>setTimeLeft(v=>v>1?v-1:v),1000);const a=setTimeout(()=>{clearInterval(t);loopRef.current?.stop();const ni=(cueIdx+1)%pat.cues.length;if(ni===0){if(round>=4){setRunning(false);setDone(true);}else{setRound(r=>r+1);setCueIdx(0);}}else setCueIdx(ni);},dur*1000);return()=>{clearInterval(t);clearTimeout(a);loopRef.current?.stop();};},[running,cueIdx,round]);
  const start=()=>{setCueIdx(0);setRound(1);setTaps(0);setDone(false);setRunning(true);};
  return(<View style={mt.cont}><View style={mt.header}><Text style={mt.title}>🌿 සිහිකල්පනාව</Text><Text style={mt.score}>⭐{taps}</Text></View><Text style={mt.hint}>ශ්වාස රිද්මය — කවය ස්පර්ශ 🌸</Text><View style={mt.patRow}>{MT_PATTERNS.map((p,i)=>(<TouchableOpacity key={i} style={[mt.patBtn,patIdx===i&&{borderColor:p.color,borderWidth:2}]} onPress={()=>{setPatIdx(i);setRunning(false);setDone(false);}}><Text style={[mt.patBtnT,patIdx===i&&{color:p.color,fontWeight:'800'}]}>{p.name}</Text></TouchableOpacity>))}</View><View style={{alignItems:'center',justifyContent:'center',marginVertical:14}}><Animated.View style={{transform:[{scale:pulse}]}}>  <TouchableOpacity onPress={()=>{if(running)setTaps(t=>t+1);else start();}} style={[mt.circle,{borderColor:pat.color}]}><LinearGradient colors={[pat.color+'33',pat.color+'11']} style={mt.circleInner}>{running?(<><Text style={[mt.circleT,{color:pat.color}]}>{pat.cues[cueIdx]}</Text><Text style={[mt.circleCount,{color:pat.color}]}>{timeLeft}</Text><Text style={mt.circleRound}>වට {round}/4</Text></>):done?(<Text style={mt.circleT}>🌸 සම්පූර්ණ!</Text>):(<Text style={mt.circleT}>▶ ස්පර්ශ</Text>)}</LinearGradient></TouchableOpacity></Animated.View></View>{done&&<LinearGradient colors={['#EDE7F6','#FCE4EC']} style={mt.doneCard}><Text style={mt.doneT}>🌸 {taps} වාරයක්! 💜</Text></LinearGradient>}</View>);
};

// MATURE GAME 3: MOOD BOARD
const MB_ITEMS=[['☀️','🌙','🌧️','⛅','🌈','🌪️'],['🌸','🌹','🥀','🌿','🍂','🌱'],['❤️','💜','💙','🖤','🤍','💛'],['😊','😔','😤','🥹','😴','💪'],['🦋','🕊️','🌊','🔥','⭐','🌙'],['🍵','🍼','📖','🎵','🏠','👶']];
const MB_LABELS=['කාලගුණය','ස්වභාවය','හැඟීම','ආකල්පය','ශක්‍යතාව','ජීවිතය'];
const MoodBoard=()=>{
  const[board,setBoard]=useState(Array(6).fill(null));const[saved,setSaved]=useState(false);const[history,setHistory]=useState([]);
  const toggle=(ri,emoji)=>{const nb=[...board];nb[ri]=nb[ri]===emoji?null:emoji;setBoard(nb);setSaved(false);};
  const save=()=>{setHistory(h=>[...h.slice(-4),{emojis:[...board],date:new Date().toLocaleDateString()}]);setSaved(true);};
  const clear=()=>{setBoard(Array(6).fill(null));setSaved(false);};
  return(<View style={mb.cont}><View style={mb.header}><Text style={mb.title}>🎭 මනෝභාව පුවරුව</Text></View><Text style={mb.hint}>ඔබේ හැඟීම් — emoji තෝරන්න 🌸</Text>{MB_ITEMS.map((row,ri)=>(<View key={ri} style={mb.row}><Text style={mb.rowLabel}>{MB_LABELS[ri]}</Text><View style={mb.rowItems}>{row.map((emoji,ei)=>(<TouchableOpacity key={ei} onPress={()=>toggle(ri,emoji)} style={[mb.item,board[ri]===emoji&&mb.itemSel]}><Text style={{fontSize:24}}>{emoji}</Text></TouchableOpacity>))}</View></View>))}<View style={mb.preview}><Text style={mb.previewLabel}>අද ඔබේ ළොව:</Text><View style={mb.previewRow}>{board.map((e,i)=>e?<Text key={i} style={{fontSize:26}}>{e}</Text>:<Text key={i} style={{fontSize:26,opacity:.2}}>○</Text>)}</View></View><View style={mb.btnRow}><TouchableOpacity style={mb.saveBtn} onPress={save}><LinearGradient colors={['#7E57C2','#E91E8C']} style={mb.saveBtnIn}><Text style={mb.saveBtnT}>{saved?'✓ සුරකිනා':'💾 සුරකින්න'}</Text></LinearGradient></TouchableOpacity><TouchableOpacity style={mb.clearBtn} onPress={clear}><Text style={mb.clearBtnT}>↺ ඉවත්</Text></TouchableOpacity></View>{history.length>0&&<View style={mb.historyBox}><Text style={mb.historyTitle}>පසුගිය:</Text>{history.slice(-3).map((h,i)=>(<View key={i} style={mb.historyItem}><Text style={mb.historyDate}>{h.date}</Text><View style={{flexDirection:'row'}}>{h.emojis.map((e,j)=>e?<Text key={j} style={{fontSize:16}}>{e}</Text>:null)}</View></View>))}</View>}</View>);
};

// MATURE GAME 4: GRATITUDE GARDEN
const GG_PROMPTS=['අද ඔබ කෘතඥ?','ළදරු ගැන ආදරය?','ඔබව රැකගත්?','ශරීරය හොඳ?','නිදහස් ගණිතය?','ශ්‍රේෂ්ඨ ජය?'];
const GG_FLOWERS=['🌸','🌺','🌹','🌻','🌷','🌼','💐','🏵️'];
const GratitudeGarden=()=>{
  const[garden,setGarden]=useState([]);const[promptIdx,setPromptIdx]=useState(0);const[answered,setAnswered]=useState(false);
  const gardenW=width-spacing.md*2-8;const gardenH=Math.floor(gardenW*0.6);
  const addFlower=()=>{if(garden.length>=12)return;setGarden(g=>[...g,{id:Date.now(),emoji:GG_FLOWERS[garden.length%GG_FLOWERS.length],x:Math.random()*0.8+0.05,y:Math.random()*0.7+0.1}]);setAnswered(true);setTimeout(()=>{setAnswered(false);setPromptIdx(i=>(i+1)%GG_PROMPTS.length);},800);};
  return(<View style={gg.cont}><View style={gg.header}><Text style={gg.title}>🌿 කෘතඥ උද්‍යානය</Text><Text style={gg.count}>🌸{garden.length}/12</Text></View><Text style={gg.hint}>සෑම "ඔව්" ස්පර්ශයකින් මලක් 🌸</Text><View style={[gg.garden,{width:gardenW,height:gardenH}]}><LinearGradient colors={['#E8F5E9','#C8E6C9']} style={StyleSheet.absoluteFillObject}/>{garden.map(f=>(<Text key={f.id} style={[gg.gardenFlower,{left:f.x*(gardenW-36),top:f.y*(gardenH-36)}]}>{f.emoji}</Text>))}{garden.length===0&&<Text style={gg.gardenEmpty}>ඔබේ උද්‍යානය 🌱</Text>}</View><LinearGradient colors={['#EDE7F6','#FCE4EC']} style={gg.promptCard}><Text style={gg.promptText}>{GG_PROMPTS[promptIdx]}</Text><TouchableOpacity style={gg.yesBtn} onPress={addFlower} disabled={answered||garden.length>=12}><LinearGradient colors={answered?['#C8E6C9','#A5D6A7']:['#7E57C2','#E91E8C']} style={gg.yesBtnIn}><Text style={gg.yesBtnT}>{answered?'🌸 ❤️':'💚 ඔව්!'}</Text></LinearGradient></TouchableOpacity><TouchableOpacity onPress={()=>setPromptIdx(i=>(i+1)%GG_PROMPTS.length)}><Text style={gg.skipT}>→ ඊළඟ</Text></TouchableOpacity></LinearGradient>{garden.length>=12&&<LinearGradient colors={['#FFF9C4','#FCE4EC']} style={gg.fullCard}><Text style={gg.fullT}>🌻 පිරිලා! 💜</Text></LinearGradient>}</View>);
};

// GAMES LIST & MAIN SCREEN
const ALL_GAMES_LIST=[
  {id:'word_search',label:'වචන සෙවීම',labelEn:'සැඟවුණු වචන සොයන්න',icon:'🔤',color:['#E8F5E9','#C8E6C9'],accent:'#2E7D32'},
  {id:'baby_interaction',label:'ළදරු බැඳීම',labelEn:'ළදරු බැඳීම',icon:'👶',color:['#FCE4EC','#F8BBD9'],accent:'#C2185B'},
  {id:'memory_match',label:'මතක ගැළපීම',labelEn:'යුගල සොයන්න',icon:'🃏',color:['#EDE7F6','#D1C4E9'],accent:'#7E57C2'},
  {id:'baby_mood',label:'ළදරු හැඟීම',labelEn:"ළදරු මනෝභාවය",icon:'😊',color:['#FFF9C4','#FFF3A0'],accent:'#F57F17'},
  {id:'self_care',label:'ස්වයං රැකවරණය',labelEn:'දෛනික රැකවරණය',icon:'🌿',color:['#E8F5E9','#A5D6A7'],accent:'#2E7D32'},
  {id:'bubble_pop',label:'බුබුළු ෆොන්',labelEn:'මල් පමණක් තෝරන්න!',icon:'🌸',color:['#E3F2FD','#BBDEFB'],accent:'#1565C0'},
  {id:'word_match',label:'වචන ගැළපීම',labelEn:'සෑම වටයකම නව වචන',icon:'💬',color:['#F3E5F5','#E1BEE7'],accent:'#7E57C2'},
  {id:'word_builder',label:'වචන ගොඩනැගීම',labelEn:'වචන සාදන්න + ඉඟි',icon:'🔠',color:['#EDE7F6','#D1C4E9'],accent:'#7E57C2'},
  {id:'pattern_repeat',label:'රටාව නැවත',labelEn:'මතක රටාව',icon:'🧠',color:['#FCE4EC','#F8BBD9'],accent:'#E91E8C'},
  {id:'spot_diff',label:'වෙනස සොයන්න',labelEn:'වෙනස සොයන්න',icon:'🔍',color:['#E8F5E9','#C8E6C9'],accent:'#2E7D32'},
  {id:'sequence_order',label:'අනුපිළිවෙල',labelEn:'පියවර පිළිවෙලට සකසන්න',icon:'🧩',color:['#F3E5F5','#E1BEE7'],accent:'#8E24AA'},
  {id:'number_seq',label:'අංක',labelEn:'1→2→3 තට්ටු කරන්න',icon:'🔢',color:['#E8F5E9','#A5D6A7'],accent:'#2E7D32'},
  {id:'coin_maze',label:'කාසි මාලිම',labelEn:'කාසි එකතු කරන්න',icon:'🪙',color:['#FFF9C4','#FFF3E0'],accent:'#F57F17'},
  {id:'rotation_puzzle',label:'කරකැවිල්ල',labelEn:'කොටස් කරකවන්න',icon:'🔄',color:['#EDE7F6','#D1C4E9'],accent:'#7E57C2'},
  {id:'sliding_puzzle',label:'ස්ලයිඩ්',labelEn:'කොටස් ලිස්සවන්න',icon:'🧩',color:['#E8F5E9','#C8E6C9'],accent:'#2E7D32'},
  {id:'emotion_journal',label:'හැඟීම් දිනපොත',labelEn:'ඔබේ මනෝභාවය සටහන් කරන්න',icon:'🎭',color:['#FCE4EC','#F8BBD9'],accent:'#E91E8C'},
  {id:'mindful_tap',label:'සිහිකල්පනාව',labelEn:'ශ්වාස රිද්මය',icon:'🌿',color:['#E8F5E9','#C8E6C9'],accent:'#2E7D32'},
  {id:'mood_board',label:'මනෝභාව පුවරුව',labelEn:'ඔබේ හැඟීම් ප්‍රකාශ කරන්න',icon:'🎨',color:['#EDE7F6','#D1C4E9'],accent:'#7E57C2'},
  {id:'gratitude_garden',label:'කෘතඥ උද්‍යානය',labelEn:'කෘතඥ උද්‍යානය',icon:'🌸',color:['#E8F5E9','#A5D6A7'],accent:'#2E7D32'},
  {id:'mandala',label:'මණ්ඩල කලා',labelEn:'මණ්ඩල කලා පාට කරන්න',icon:'🔮',color:['#EDE7F6','#D1C4E9'],accent:'#7E57C2'},
  {id:'colouring',label:'රූප පාටකිරීම',labelEn:'රූප පාට කරන්න',icon:'🎨',color:['#FCE4EC','#F8BBD9'],accent:'#E91E8C'},
];
const MATURE_IDS=['emotion_journal','mindful_tap','mood_board','gratitude_garden'];

const ActivityScreen=({navigation,route})=>{
  const[selAct,setSelAct]=useState(null);const[selGame,setSelGame]=useState(null);const[view,setView]=useState('list');const[done,setDone]=useState(false);
  useEffect(()=>{if(route?.params?.activityId){const a=ALL_ACTIVITIES.find(x=>x.id===route.params.activityId);if(a){setSelAct(a);setView('activity');setDone(false);}}if(route?.params?.gameId){const found=ALL_GAMES_LIST.find(x=>x.id===route.params.gameId);if(found){setSelGame(found);setView('game');}}},[route?.params]);
  const renderAct=(act)=>{switch(act.type){case'breathing':return<BreathingEx activity={act} onComplete={()=>setDone(true)}/>;case'guided':return<GuidedAct activity={act} onComplete={()=>setDone(true)}/>;case'prompts':return<PromptsAct activity={act}/>;default:return<GuidedAct activity={act} onComplete={()=>setDone(true)}/>;}};
  const renderGame=(id)=>{switch(id){
    case'word_search':return<WordSearch/>;case'baby_interaction':return<BabyInteractionGame/>;case'memory_match':return<MemoryMatch/>;
    case'baby_mood':return<BabyMoodGuess/>;case'self_care':return<SelfCareQuest/>;case'bubble_pop':return<BubblePop/>;
    case'word_match':return<WordMatchGame/>;case'word_builder':return<WordBuilder/>;case'pattern_repeat':return<PatternRepeat/>;
    case'spot_diff':return<SpotDifference/>;case'sequence_order':return<SequenceOrder/>;case'number_seq':return<NumberSeq/>;
    case'coin_maze':return<CoinMaze/>;case'rotation_puzzle':return<RotationPuzzle/>;case'sliding_puzzle':return<SlidingPuzzle/>;
    case'emotion_journal':return<EmotionJournal/>;case'mindful_tap':return<MindfulTap/>;case'mood_board':return<MoodBoard/>;
    case'gratitude_garden':return<GratitudeGarden/>;
    case'mandala':case'colouring':navigation.navigate('Art');return null;
    default:return<BubblePop/>;
  }};
  const goBack=()=>{setView('list');setSelAct(null);setSelGame(null);setDone(false);};
  if(view==='activity'&&selAct)return(<View style={s.container}><LinearGradient colors={['#F8F4FF','#F0FAFF']} style={s.gradient}><ScrollView contentContainerStyle={s.scroll}><TouchableOpacity onPress={goBack} style={s.backBtn}><Text style={s.backText}>← ආපසු</Text></TouchableOpacity><Text style={s.actTitle}>{selAct.label}</Text><Text style={s.actSub}>{selAct.desc}</Text>{renderAct(selAct)}{done&&<LinearGradient colors={['#EDE7F6','#FCE4EC']} style={s.banner}><Text style={s.bannerT}>🌸 සම්පූර්ණ! 💜</Text></LinearGradient>}<View style={{height:110}}/></ScrollView></LinearGradient></View>);
  if(view==='game'&&selGame)return(<View style={s.container}><LinearGradient colors={['#F8F4FF','#F0FAFF']} style={s.gradient}><ScrollView contentContainerStyle={s.scroll}><TouchableOpacity onPress={goBack} style={s.backBtn}><Text style={s.backText}>← ආපසු</Text></TouchableOpacity>{renderGame(selGame.id)}<View style={{height:110}}/></ScrollView></LinearGradient></View>);
  return(<View style={s.container}><LinearGradient colors={['#F8F4FF','#F0FAFF']} style={s.gradient}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={s.scroll}>
    <Text style={s.pageTitle}>ක්‍රියාකාරකම් සහ ක්‍රීඩා 🌸</Text><Text style={s.pageSub}>ඔබේ යහපැවැත්ම 💜</Text>
    <TouchableOpacity onPress={()=>navigation.navigate('Art')} style={s.artBanner}><Text style={s.artBannerIcon}>🎨</Text><View style={s.artBannerInfo}><Text style={s.artBannerTitle}>කලා සහ රූප</Text><Text style={s.artBannerSub}>10 මණ්ඩල + 10 රූප</Text></View><Text style={s.artBannerArrow}>→</Text></TouchableOpacity>
    <Text style={[s.sectionLabel,{color:'#E91E8C'}]}>💜 සුව ලබාදෙන ක්‍රීඩා</Text>
    <View style={s.gamesGrid}>{ALL_GAMES_LIST.filter(g=>MATURE_IDS.includes(g.id)).map(game=>(<TouchableOpacity key={game.id} style={s.gameWrap} onPress={()=>{setSelGame(game);setView('game');}}><LinearGradient colors={game.color} style={s.gameCard}><Text style={s.gameIcon}>{game.icon}</Text><Text style={s.gameLabel}>{game.label}</Text><Text style={s.gameDesc}>{game.labelEn}</Text></LinearGradient></TouchableOpacity>))}</View>
    <Text style={[s.sectionLabel,{color:'#7E57C2'}]}>🎮 සියලු ක්‍රීඩා</Text>
    <View style={s.gamesGrid}>{ALL_GAMES_LIST.map(game=>(<TouchableOpacity key={game.id} style={s.gameWrap} onPress={()=>{setSelGame(game);setView('game');}}><LinearGradient colors={game.color} style={s.gameCard}><Text style={s.gameIcon}>{game.icon}</Text><Text style={s.gameLabel}>{game.label}</Text><Text style={s.gameDesc}>{game.labelEn}</Text></LinearGradient></TouchableOpacity>))}</View>
    <View style={{height:80}}/>
  </ScrollView></LinearGradient></View>);
};

const bx=StyleSheet.create({cont:{alignItems:'center',padding:20},intro:{borderRadius:30,padding:20,marginBottom:16,alignItems:'center'},introText:{fontSize:16,color:'white',fontWeight:'700'},circleWrap:{marginVertical:24},circleOuter:{width:180,height:180,borderRadius:100,overflow:'hidden'},circleInner:{flex:1,justifyContent:'center',alignItems:'center'},icon:{fontSize:48,marginBottom:10},count:{fontSize:44,fontWeight:'800',color:'#E91E8C'},info:{marginTop:20,alignItems:'center'},phaseName:{fontSize:20,fontWeight:'800'},phaseInstr:{fontSize:13,color:'#666',marginTop:4},cycleT:{fontSize:13,color:'#aaa',marginTop:6},startBtn:{marginTop:20,borderRadius:999,overflow:'hidden'},startBtnIn:{paddingHorizontal:28,paddingVertical:12},startBtnText:{color:'white',fontWeight:'800',fontSize:16},done:{borderRadius:30,padding:24,alignItems:'center'},doneEmoji:{fontSize:40},doneTitle:{fontSize:20,fontWeight:'800',color:'#2E7D32',marginVertical:8},doneMsg:{fontSize:13,color:'#666'}});
const gd=StyleSheet.create({intro:{borderRadius:30,padding:20,marginBottom:16,alignItems:'center'},introText:{fontSize:16,color:'white',fontWeight:'700'},startBtn:{marginTop:20,borderRadius:999,overflow:'hidden'},startBtnIn:{paddingHorizontal:28,paddingVertical:12},startBtnText:{color:'white',fontWeight:'800',fontSize:16},dotsRow:{flexDirection:'row',justifyContent:'center',marginVertical:12,gap:8},dot:{width:12,height:12,borderRadius:6,backgroundColor:'#ddd'},dotA:{backgroundColor:'#E91E8C',width:20},dotD:{backgroundColor:'#7E57C2'},stepCard:{borderRadius:30,padding:20,marginVertical:12},stepLabel:{fontSize:22,fontWeight:'800'},stepText:{fontSize:14,color:'#444',marginTop:8,lineHeight:22},timerRow:{flexDirection:'row',alignItems:'center',justifyContent:'center',marginTop:12,gap:16},timerCircle:{width:48,height:48,borderRadius:24,backgroundColor:'white',justifyContent:'center',alignItems:'center',shadowColor:'#000',shadowOffset:{width:0,height:2},shadowOpacity:0.1,shadowRadius:4,elevation:2},timerCount:{fontSize:26,fontWeight:'800'},timerBg:{flex:1,height:6,backgroundColor:'#ddd',borderRadius:3,overflow:'hidden',maxWidth:180},timerFill:{height:'100%'},done:{borderRadius:30,padding:24,alignItems:'center'},doneEmoji:{fontSize:40},doneTitle:{fontSize:20,fontWeight:'800',color:'#2E7D32',marginVertical:8}});
const pr=StyleSheet.create({intro:{borderRadius:30,padding:20,marginBottom:16,alignItems:'center'},introText:{fontSize:16,color:'white',fontWeight:'700'},counter:{textAlign:'center',fontSize:12,color:'#999',marginBottom:6},card:{borderRadius:30,padding:24,marginVertical:12},cardEmoji:{fontSize:32,textAlign:'center',marginBottom:10},cardText:{fontSize:16,lineHeight:24,color:'#333',textAlign:'center'},btnRow:{flexDirection:'row',justifyContent:'space-between',marginTop:20},prev:{borderRadius:999,paddingHorizontal:18,paddingVertical:10,backgroundColor:'#ddd'},prevT:{fontWeight:'600'},next:{borderRadius:999,overflow:'hidden'},nextIn:{paddingHorizontal:22,paddingVertical:10},nextT:{color:'white',fontWeight:'800'},done:{borderRadius:30,padding:12,alignItems:'center'},doneT:{fontWeight:'700',color:'#7E57C2'}});
const ws=StyleSheet.create({cont:{padding:spacing.md},header:{flexDirection:'row',justifyContent:'space-between',marginBottom:8},title:{fontSize:18,fontWeight:'800'},badge:{backgroundColor:'#E8F5E9',paddingHorizontal:12,paddingVertical:4,borderRadius:20},badgeTxt:{fontWeight:'700',color:'#2E7D32'},subtitle:{fontSize:13,color:'#666',marginBottom:12},gridWrap:{alignSelf:'center',marginVertical:12},gridRow:{flexDirection:'row',justifyContent:'center'},cell:{borderWidth:1,borderColor:'#ccc',justifyContent:'center',alignItems:'center',margin:1.5,backgroundColor:'#FFF',borderRadius:6},cellTxt:{fontWeight:'600',color:'#222'},cellSel:{backgroundColor:'#FFE0F0'},cellFound:{backgroundColor:'#D9F0D9'},cellWrong:{backgroundColor:'#FFCCCC'},cellTxtF:{color:'#1B5E20'},cellTxtS:{color:'#E91E8C'},wordList:{flexDirection:'row',flexWrap:'wrap',justifyContent:'center',marginVertical:12,gap:6},chip:{paddingHorizontal:12,paddingVertical:5,borderRadius:40,backgroundColor:'#EDE7F6'},chipFound:{backgroundColor:'#C8E6C9'},chipTxt:{fontSize:12,fontWeight:'600'},chipTxtF:{color:'#1B5E20',textDecorationLine:'line-through'},diffRow:{flexDirection:'row',justifyContent:'center',gap:8,marginVertical:12},diffBtn:{paddingHorizontal:14,paddingVertical:6,borderRadius:40,backgroundColor:'#eee'},diffBtnOn:{backgroundColor:'#7E57C2'},diffTxt:{fontSize:12},diffTxtOn:{color:'white',fontWeight:'bold'},newBtn:{marginTop:6,alignSelf:'center',paddingHorizontal:18,paddingVertical:8,borderRadius:40,backgroundColor:'#ddd'},newBtnTxt:{fontSize:12},wonCard:{borderRadius:30,padding:16,marginVertical:12,alignItems:'center'},wonEmoji:{fontSize:32},wonTitle:{fontWeight:'800',color:'#2E7D32'}});
const bi=StyleSheet.create({cont:{padding:spacing.md},header:{flexDirection:'row',justifyContent:'space-between',marginBottom:16},title:{fontSize:20,fontWeight:'800'},count:{fontSize:12,color:'#E91E8C'},babyCard:{borderRadius:40,padding:20,alignItems:'center',marginBottom:12},babyEmoji:{fontSize:70,marginBottom:6},moodLabel:{fontSize:12,fontWeight:'600',color:'#555'},responseBox:{flexDirection:'row',backgroundColor:'white',borderRadius:40,paddingHorizontal:12,paddingVertical:6,marginTop:12,gap:6},responseEmoji:{fontSize:16},responseText:{fontSize:12,color:'#222'},actLabel:{fontWeight:'800',marginTop:10,marginBottom:6},actGrid:{flexDirection:'row',flexWrap:'wrap',justifyContent:'center',gap:10,marginBottom:14},actWrap:{borderRadius:40,overflow:'hidden'},actBtn:{paddingHorizontal:18,paddingVertical:10},actBtnText:{fontWeight:'700',fontSize:13},badge:{borderRadius:30,padding:12,alignItems:'center',marginTop:10},badgeText:{fontWeight:'800',color:'#7E57C2'}});
const mm=StyleSheet.create({cont:{padding:spacing.md},header:{flexDirection:'row',justifyContent:'space-between',marginBottom:8},title:{fontSize:19,fontWeight:'800'},stats:{flexDirection:'row',gap:10},statChip:{backgroundColor:'#F3E5F5',paddingHorizontal:12,paddingVertical:3,borderRadius:20},statTxt:{fontSize:12,fontWeight:'700'},hint:{fontSize:12,color:'#666',marginBottom:14},grid:{flexDirection:'row',flexWrap:'wrap',justifyContent:'center',gap:8},card:{borderRadius:16,overflow:'hidden'},cardInner:{flex:1,justifyContent:'center',alignItems:'center'},resetBtn:{alignSelf:'center',marginTop:18,backgroundColor:'#EDE7F6',paddingHorizontal:20,paddingVertical:8,borderRadius:40},resetBtnT:{fontWeight:'700'}});
const bm=StyleSheet.create({cont:{padding:spacing.md},header:{flexDirection:'row',justifyContent:'space-between',marginBottom:12},title:{fontSize:20,fontWeight:'800'},score:{fontSize:14,fontWeight:'700',color:'#E91E8C'},faceCard:{borderRadius:50,padding:20,alignItems:'center',marginBottom:12},babyFace:{fontSize:90,marginVertical:12},faceLabel:{fontSize:12,color:'#777'},resultBadge:{marginTop:10,paddingHorizontal:14,paddingVertical:5,borderRadius:30},correctBadge:{backgroundColor:'#A5D6A7'},wrongBadge:{backgroundColor:'#FFCDD2'},resultText:{fontWeight:'800'},hintText:{marginTop:8,fontSize:12,color:'#7E57C2'},options:{flexDirection:'row',flexWrap:'wrap',justifyContent:'center',gap:12,marginVertical:16},optBtn:{backgroundColor:'white',paddingHorizontal:20,paddingVertical:12,borderRadius:40,borderWidth:1,borderColor:'#ddd'},optCorrect:{backgroundColor:'#A5D6A7',borderColor:'#2E7D32'},optWrong:{backgroundColor:'#FFCDD2',borderColor:'#C62828'},optText:{fontWeight:'600'},btnRow:{flexDirection:'row',justifyContent:'center',gap:20,marginTop:8},hintBtn:{borderWidth:1,borderColor:'#7E57C2',paddingHorizontal:16,paddingVertical:8,borderRadius:40},hintBtnT:{color:'#7E57C2',fontWeight:'600'},nextBtn:{borderRadius:40,overflow:'hidden'},nextBtnIn:{paddingHorizontal:22,paddingVertical:10},nextBtnT:{color:'white',fontWeight:'800'}});
const sc=StyleSheet.create({cont:{padding:spacing.md},header:{flexDirection:'row',justifyContent:'space-between',marginBottom:12},title:{fontSize:20,fontWeight:'800'},pts:{fontSize:18,fontWeight:'800',color:'#F57F17'},badgeCard:{borderRadius:30,padding:16,alignItems:'center',marginBottom:10},badgeEmoji:{fontSize:34},badgeName:{fontSize:16,fontWeight:'800',marginVertical:4},nextBadgeT:{fontSize:11,color:'#777'},progressBg:{height:6,backgroundColor:'#ddd',borderRadius:3,width:'100%',marginVertical:6},progressFill:{height:'100%',backgroundColor:'#7E57C2',borderRadius:3},progressT:{fontSize:10,color:'#777'},popup:{position:'absolute',top:-30,left:20,right:20,padding:8,borderRadius:40,alignItems:'center',zIndex:10},popupEmoji:{fontSize:24},popupT:{fontWeight:'bold',fontSize:12},taskLbl:{fontWeight:'800',marginVertical:8},taskCard:{flexDirection:'row',alignItems:'center',padding:12,borderRadius:28,marginBottom:8,gap:12},taskDone:{opacity:0.7},taskIcon:{fontSize:26},taskLabel2:{flex:1,fontWeight:'500'},taskLblDone:{textDecorationLine:'line-through',color:'#777'},taskPts:{color:'#7E57C2',fontWeight:'800'},cb:{width:26,height:26,borderRadius:13,borderWidth:2,borderColor:'#aaa',justifyContent:'center',alignItems:'center'},cbDone:{backgroundColor:'#2E7D32',borderColor:'#2E7D32'},cbCheck:{color:'white',fontWeight:'bold',fontSize:14},note:{borderRadius:30,padding:14,marginTop:12,alignItems:'center'},noteT:{fontSize:12,color:'#666'}});
const bp=StyleSheet.create({cont:{padding:spacing.md},header:{flexDirection:'row',justifyContent:'space-between',marginBottom:6},title:{fontSize:20,fontWeight:'800'},stats:{flexDirection:'row',gap:12},scoreT:{fontWeight:'800',color:'#E91E8C'},livesT:{fontWeight:'700'},timerT:{fontWeight:'600',color:'#1565C0'},rule:{fontSize:10,color:'#999',marginBottom:12},area:{minHeight:300,position:'relative',marginVertical:8},bubble:{position:'absolute',justifyContent:'center',alignItems:'center'},bubbleGrad:{flex:1,justifyContent:'center',alignItems:'center'},startBtn:{alignSelf:'center',borderRadius:999,overflow:'hidden',marginTop:100},startBtnIn:{paddingHorizontal:36,paddingVertical:14},startBtnT:{color:'white',fontWeight:'800',fontSize:18},gameOverCard:{borderRadius:40,padding:20,alignItems:'center',marginVertical:50},gameOverT:{fontSize:18,fontWeight:'800',marginBottom:8},gameOverScore:{fontSize:32,fontWeight:'800',color:'#7E57C2'},retryBtn:{marginTop:14,backgroundColor:'#ddd',paddingHorizontal:22,paddingVertical:8,borderRadius:40},retryBtnT:{fontWeight:'700'}});
const wm=StyleSheet.create({cont:{padding:spacing.md},header:{flexDirection:'row',justifyContent:'space-between',marginBottom:8},title:{fontSize:20,fontWeight:'800'},score:{fontSize:14,color:'#E91E8C',fontWeight:'700'},hint:{fontSize:12,color:'#777',marginBottom:12},cols:{flexDirection:'row',justifyContent:'space-between',gap:12},col:{flex:1,gap:8},card:{backgroundColor:'white',padding:14,borderRadius:30,alignItems:'center',shadowColor:'#000',shadowOffset:{width:0,height:1},shadowOpacity:0.05,shadowRadius:2,elevation:1},cardR:{backgroundColor:'#FAFAFA'},cardT:{fontWeight:'700',fontSize:14},emoji:{fontSize:24},sel:{borderWidth:2,borderColor:'#E91E8C'},done2:{opacity:0.5,backgroundColor:'#E8F5E9'},bad:{backgroundColor:'#FFCDD2'}});
const wb=StyleSheet.create({cont:{padding:spacing.md},header:{flexDirection:'row',justifyContent:'space-between',marginBottom:6},title:{fontSize:20,fontWeight:'800'},score:{fontSize:14,fontWeight:'700',color:'#E91E8C'},subhint:{fontSize:11,color:'#7E57C2',marginBottom:12},inputBox:{borderRadius:40,backgroundColor:'white',paddingVertical:18,paddingHorizontal:20,marginVertical:15,alignItems:'center',shadowColor:'#000',shadowOffset:{width:0,height:2},shadowOpacity:0.1,shadowRadius:8,elevation:2},inputText:{fontSize:26,letterSpacing:4,fontWeight:'800',color:'#222'},msg:{fontSize:12,marginTop:6,fontWeight:'500'},letters:{flexDirection:'row',flexWrap:'wrap',justifyContent:'center',gap:12,marginVertical:12},letterBtn:{backgroundColor:'#EDE7F6',width:58,height:58,borderRadius:29,justifyContent:'center',alignItems:'center'},letterT:{fontSize:26,fontWeight:'700',color:'#7E57C2'},actionRow:{flexDirection:'row',justifyContent:'center',gap:16,marginTop:6},backBtn:{backgroundColor:'#eee',width:54,height:54,borderRadius:27,justifyContent:'center',alignItems:'center'},backBtnT:{fontSize:26},clearBtn:{backgroundColor:'#eee',width:54,height:54,borderRadius:27,justifyContent:'center',alignItems:'center'},clearBtnT:{fontSize:18,fontWeight:'800'},submitBtn:{borderRadius:40,overflow:'hidden'},submitBtnIn:{paddingHorizontal:20,paddingVertical:14},submitBtnT:{color:'white',fontWeight:'800'},hintBtn:{backgroundColor:'#EDE7F6',alignSelf:'center',paddingHorizontal:20,paddingVertical:10,borderRadius:40,marginVertical:12},hintBtnT:{fontWeight:'700',color:'#7E57C2'},foundLabel:{fontWeight:'800',marginTop:8,marginBottom:6},foundList:{flexDirection:'row',flexWrap:'wrap',gap:8,marginBottom:14},foundChip:{backgroundColor:'#E8F5E9',paddingHorizontal:12,paddingVertical:5,borderRadius:20},foundChipT:{fontWeight:'600',color:'#2E7D32'},newBtn:{alignSelf:'center',backgroundColor:'#ddd',paddingHorizontal:22,paddingVertical:8,borderRadius:40},newBtnT:{fontWeight:'700'}});
const pat=StyleSheet.create({cont:{padding:spacing.md},header:{flexDirection:'row',justifyContent:'space-between',marginBottom:6},title:{fontSize:20,fontWeight:'800'},score:{fontSize:14,fontWeight:'700',color:'#E91E8C'},hint:{fontSize:12,color:'#666',marginBottom:12},dotsRow:{flexDirection:'row',justifyContent:'center',marginVertical:12,gap:8},dot:{height:10,borderRadius:5},grid:{flexDirection:'row',flexWrap:'wrap',justifyContent:'center',gap:8,marginVertical:16},pad:{borderRadius:20,justifyContent:'center',alignItems:'center',margin:4},padIcon:{fontSize:26},padName:{fontSize:10,fontWeight:'700',color:'white',marginTop:4},startBtn:{alignSelf:'center',marginTop:20,borderRadius:999,overflow:'hidden'},startBtnIn:{paddingHorizontal:28,paddingVertical:12},startBtnT:{color:'white',fontWeight:'800'}});
const spd=StyleSheet.create({cont:{padding:spacing.md},header:{flexDirection:'row',justifyContent:'space-between',marginBottom:6},title:{fontSize:20,fontWeight:'800'},score:{backgroundColor:'#E8F5E9',paddingHorizontal:10,paddingVertical:2,borderRadius:20,fontWeight:'700'},sceneTitle:{fontWeight:'800',textAlign:'center',marginVertical:6},msg:{textAlign:'center',marginVertical:6,fontSize:12},hint:{fontSize:10,color:'#999',textAlign:'center'},panels:{flexDirection:'row',justifyContent:'space-between',gap:12,marginVertical:14},panel:{borderRadius:28,overflow:'hidden',padding:8,position:'relative'},panelLabel:{position:'absolute',top:8,left:12,fontSize:10,backgroundColor:'rgba(255,255,255,0.8)',paddingHorizontal:6,paddingVertical:2,borderRadius:12,zIndex:2},sceneItem:{position:'absolute',justifyContent:'center',alignItems:'center'},foundMark:{position:'absolute',top:-8,right:-8,backgroundColor:'#2E7D32',color:'white',fontSize:10,paddingHorizontal:4,borderRadius:12},actions:{flexDirection:'row',justifyContent:'center',gap:20,marginVertical:12},hintBtn:{borderWidth:1,borderColor:'#7E57C2',paddingHorizontal:16,paddingVertical:6,borderRadius:40},hintBtnT:{color:'#7E57C2',fontWeight:'600'},nextBtn:{backgroundColor:'#EDE7F6',paddingHorizontal:20,paddingVertical:6,borderRadius:40},nextBtnT:{fontWeight:'700'}});
const so=StyleSheet.create({cont:{padding:spacing.md},header:{flexDirection:'row',justifyContent:'space-between',marginBottom:8},title:{fontSize:20,fontWeight:'800'},score:{fontSize:16,fontWeight:'800',color:'#F57F17'},hint:{fontSize:12,color:'#666',marginBottom:8},seqTitle:{fontSize:18,fontWeight:'800',marginVertical:12,textAlign:'center'},item:{flexDirection:'row',alignItems:'center',backgroundColor:'white',padding:14,borderRadius:30,marginBottom:8,gap:14},itemSel:{borderWidth:2,borderColor:'#E91E8C'},itemDone:{backgroundColor:'#E8F5E9',opacity:0.7},itemNum:{fontWeight:'800',fontSize:20,width:36,color:'#7E57C2'},itemT:{fontSize:16,fontWeight:'600'}});
const cm=StyleSheet.create({cont:{padding:spacing.md},header:{flexDirection:'row',justifyContent:'space-between',marginBottom:6},title:{fontSize:20,fontWeight:'800'},score:{fontSize:18,fontWeight:'800',color:'#F57F17'},hint:{fontSize:11,color:'#999',marginBottom:12},cell:{borderWidth:1,borderColor:'#ccc',justifyContent:'center',alignItems:'center'},wall:{backgroundColor:'#3E2723'},player:{backgroundColor:'#FFE0F0',borderWidth:2,borderColor:'#E91E8C'},exit:{backgroundColor:'#FFF9C4'},dpad:{flexDirection:'column',alignItems:'center',marginVertical:16},arrowRow:{flexDirection:'row',gap:30,marginVertical:6},arrowBtn:{backgroundColor:'#EDE7F6',width:60,height:60,borderRadius:30,justifyContent:'center',alignItems:'center'},arrowT:{fontSize:28,fontWeight:'800',color:'#7E57C2'},resetBtn:{alignSelf:'center',backgroundColor:'#ddd',width:54,height:54,borderRadius:27,justifyContent:'center',alignItems:'center',marginTop:8},resetBtnT:{fontSize:24,fontWeight:'800'}});
const ns=StyleSheet.create({cont:{padding:spacing.md},header:{flexDirection:'row',justifyContent:'space-between',marginBottom:8},title:{fontSize:20,fontWeight:'800'},score:{fontSize:16,fontWeight:'800',color:'#F57F17'},hint:{fontSize:12,color:'#777',marginBottom:12},infoRow:{flexDirection:'row',justifyContent:'space-between',marginBottom:12},infoT:{fontSize:12,fontWeight:'500'},area:{minHeight:300,position:'relative'},numBtn:{position:'absolute',width:58,height:58,borderRadius:29,backgroundColor:'#EDE7F6',justifyContent:'center',alignItems:'center'},numBtnDone:{backgroundColor:'#C8E6C9'},numBtnWrong:{backgroundColor:'#FFCDD2'},numT:{fontSize:22,fontWeight:'800'},resetBtn:{alignSelf:'center',marginTop:20,backgroundColor:'#ddd',width:54,height:54,borderRadius:27,justifyContent:'center',alignItems:'center'},resetBtnT:{fontSize:24,fontWeight:'800'}});
const rp=StyleSheet.create({cont:{padding:spacing.md},header:{flexDirection:'row',justifyContent:'space-between',marginBottom:8},title:{fontSize:20,fontWeight:'800'},score:{fontSize:16,fontWeight:'800',color:'#7E57C2'},hint:{fontSize:12,color:'#777',marginBottom:10},wonBanner:{borderRadius:30,padding:12,alignItems:'center',marginBottom:12},wonT:{fontWeight:'800',color:'#2E7D32'},grid:{flexDirection:'row',flexWrap:'wrap',justifyContent:'center',gap:12,marginVertical:16},tile:{borderRadius:20,justifyContent:'center',alignItems:'center',backgroundColor:'#F3E5F5'},tileDone:{backgroundColor:'#E8F5E9',borderWidth:2,borderColor:'#2E7D32'},shuffleBtn:{alignSelf:'center',backgroundColor:'#ddd',width:54,height:54,borderRadius:27,justifyContent:'center',alignItems:'center'},shuffleBtnT:{fontSize:24}});
const slp=StyleSheet.create({cont:{padding:spacing.md},header:{flexDirection:'row',justifyContent:'space-between',marginBottom:8},title:{fontSize:20,fontWeight:'800'},score:{fontSize:16,fontWeight:'800',color:'#E91E8C'},hint:{fontSize:12,color:'#777',marginBottom:10},grid:{flexDirection:'row',flexWrap:'wrap',justifyContent:'center',gap:8},tile:{borderRadius:18,backgroundColor:'#EDE7F6',justifyContent:'center',alignItems:'center',margin:4},empty:{backgroundColor:'#F5F5F5'},correct:{backgroundColor:'#E8F5E9',borderWidth:2,borderColor:'#2E7D32'},resetBtn:{alignSelf:'center',marginTop:20,backgroundColor:'#ddd',width:54,height:54,borderRadius:27,justifyContent:'center',alignItems:'center'},resetBtnT:{fontSize:24}});
const ej=StyleSheet.create({cont:{padding:spacing.md},header:{flexDirection:'row',justifyContent:'space-between',marginBottom:6},title:{fontSize:20,fontWeight:'800'},count:{fontSize:12,color:'#E91E8C'},hint:{fontSize:12,color:'#777',marginBottom:16},grid:{flexDirection:'row',flexWrap:'wrap',justifyContent:'center',gap:12},emotionBtn:{width:80,height:80,borderRadius:40,justifyContent:'center',alignItems:'center'},emotionEmoji:{fontSize:36},emotionLabel:{fontSize:10,fontWeight:'600',marginTop:4},reflCard:{borderRadius:40,padding:20,alignItems:'center',marginVertical:16},reflEmoji:{fontSize:48},reflLabel:{fontSize:20,fontWeight:'800',marginVertical:6},reflText:{fontSize:13,textAlign:'center',lineHeight:20,marginBottom:14},saveBtn:{borderRadius:999,overflow:'hidden',marginVertical:6},saveBtnIn:{paddingHorizontal:22,paddingVertical:10},saveBtnT:{color:'white',fontWeight:'800'},cancelT:{color:'#666',marginTop:8,fontSize:12},journalList:{marginTop:20},journalTitle:{fontWeight:'800',marginBottom:8},journalItem:{flexDirection:'row',gap:8,alignItems:'center',backgroundColor:'#F5F5F5',paddingHorizontal:12,paddingVertical:8,borderRadius:30,marginBottom:6},jEmoji:{fontSize:18},jLabel:{flex:1,fontWeight:'500'},jTime:{fontSize:10,color:'#777'}});
const mt=StyleSheet.create({cont:{padding:spacing.md},header:{flexDirection:'row',justifyContent:'space-between',marginBottom:8},title:{fontSize:20,fontWeight:'800'},score:{fontSize:16,fontWeight:'800',color:'#F57F17'},hint:{fontSize:12,color:'#666',marginBottom:16},patRow:{flexDirection:'row',justifyContent:'center',gap:12,marginBottom:14},patBtn:{borderRadius:40,paddingHorizontal:14,paddingVertical:8,backgroundColor:'white'},patBtnT:{fontSize:13,color:'#555'},circle:{width:200,height:200,borderRadius:100,borderWidth:4,justifyContent:'center',alignItems:'center'},circleInner:{width:186,height:186,borderRadius:93,justifyContent:'center',alignItems:'center'},circleT:{fontSize:18,fontWeight:'800',textAlign:'center'},circleCount:{fontSize:32,fontWeight:'800',marginTop:6},circleRound:{fontSize:12,color:'#777',marginTop:4},doneCard:{borderRadius:40,padding:16,alignItems:'center',marginVertical:20},doneT:{fontWeight:'800',color:'#2E7D32'}});
const mb=StyleSheet.create({cont:{padding:spacing.md},header:{marginBottom:8},title:{fontSize:20,fontWeight:'800'},hint:{fontSize:12,color:'#666',marginBottom:16},row:{marginBottom:14},rowLabel:{fontWeight:'800',marginBottom:6,fontSize:13},rowItems:{flexDirection:'row',flexWrap:'wrap',gap:12},item:{backgroundColor:'white',padding:8,borderRadius:40,borderWidth:1,borderColor:'#ddd'},itemSel:{backgroundColor:'#FFE0F0',borderColor:'#E91E8C'},preview:{marginVertical:16,alignItems:'center'},previewLabel:{fontSize:12,color:'#777'},previewRow:{flexDirection:'row',gap:12,marginTop:8},btnRow:{flexDirection:'row',justifyContent:'center',gap:20,marginVertical:16},saveBtn:{borderRadius:40,overflow:'hidden'},saveBtnIn:{paddingHorizontal:20,paddingVertical:10},saveBtnT:{color:'white',fontWeight:'800'},clearBtn:{borderWidth:1,borderColor:'#7E57C2',paddingHorizontal:20,paddingVertical:10,borderRadius:40},clearBtnT:{color:'#7E57C2',fontWeight:'600'},historyBox:{marginTop:16},historyTitle:{fontWeight:'800',marginBottom:6},historyItem:{flexDirection:'row',gap:12,alignItems:'center',marginBottom:6,flexWrap:'wrap'},historyDate:{fontSize:10,color:'#777',width:70}});
const gg=StyleSheet.create({cont:{padding:spacing.md},header:{flexDirection:'row',justifyContent:'space-between',marginBottom:6},title:{fontSize:20,fontWeight:'800'},count:{fontSize:12,color:'#E91E8C'},hint:{fontSize:12,color:'#777',marginBottom:12},garden:{borderRadius:40,overflow:'hidden',marginVertical:14,alignSelf:'center',position:'relative'},gardenFlower:{position:'absolute',fontSize:30},gardenEmpty:{position:'absolute',top:'40%',alignSelf:'center',color:'#888',fontSize:13},promptCard:{borderRadius:40,padding:20,alignItems:'center',marginVertical:12},promptText:{fontSize:16,fontWeight:'700',textAlign:'center',marginBottom:14},yesBtn:{borderRadius:999,overflow:'hidden',width:'100%',marginBottom:8},yesBtnIn:{paddingVertical:12,alignItems:'center'},yesBtnT:{color:'white',fontWeight:'800',fontSize:16},skipT:{fontSize:12,color:'#7E57C2',marginTop:8},fullCard:{borderRadius:30,padding:12,alignItems:'center',marginTop:12}});
const s=StyleSheet.create({container:{flex:1},gradient:{flex:1},scroll:{paddingHorizontal:spacing.md,paddingTop:spacing.md,paddingBottom:40},backBtn:{marginBottom:spacing.md},backText:{fontSize:16,color:'#7E57C2',fontWeight:'600'},actTitle:{fontSize:26,fontWeight:'900',marginBottom:4},actSub:{fontSize:13,color:'#666',marginBottom:24,lineHeight:20},banner:{borderRadius:28,padding:12,marginVertical:20,alignItems:'center'},bannerT:{fontWeight:'800',color:'#7E57C2'},pageTitle:{fontSize:28,fontWeight:'900',marginBottom:6},pageSub:{fontSize:13,color:'#777',marginBottom:24},artBanner:{flexDirection:'row',alignItems:'center',backgroundColor:'white',borderRadius:34,padding:14,marginBottom:24,gap:14},artBannerIcon:{fontSize:36},artBannerInfo:{flex:1},artBannerTitle:{fontSize:17,fontWeight:'800'},artBannerSub:{fontSize:12,color:'#777'},artBannerArrow:{fontSize:24,color:'#ccc'},sectionLabel:{fontSize:18,fontWeight:'800',marginBottom:14,letterSpacing:-0.3},gamesGrid:{flexDirection:'row',flexWrap:'wrap',justifyContent:'space-between',marginBottom:24},gameWrap:{width:'48%',marginBottom:12},gameCard:{padding:14,borderRadius:28,alignItems:'center'},gameIcon:{fontSize:32,marginBottom:8},gameLabel:{fontSize:14,fontWeight:'800',textAlign:'center'},gameDesc:{fontSize:10,color:'#666',textAlign:'center',marginTop:4}});

export default ActivityScreen;